import type { Handler } from '@netlify/functions';
import { adminAuth, adminDb } from '../../api/_lib/firebase-admin';
import { FieldValue } from 'firebase-admin/firestore';

const json = (statusCode:number, body:Record<string,unknown>) => ({statusCode,headers:{'Content-Type':'application/json','Cache-Control':'no-store'},body:JSON.stringify(body)});
const bearer=(event:any)=>{const h=event.headers?.authorization||event.headers?.Authorization||'';return h.startsWith('Bearer ')?h.slice(7):''};
const roleOf=(v:unknown)=>String(v||'').trim().toUpperCase();
const staffRoles=['TUTOR','STAFF','INSTRUCTOR'];
const adminRoles=['ADMIN','SUPER_ADMIN','CONTENT_ADMIN','EDUCATION_ADMIN','SERVICES_ADMIN','MARKETING_ADMIN','SUPPORT_ADMIN'];
async function caller(event:any){const raw=bearer(event);if(!raw)throw new Error('AUTH');const decoded=await adminAuth.verifyIdToken(raw);const snap=await adminDb.collection('users').doc(decoded.uid).get();if(!snap.exists)throw new Error('PROFILE');return {uid:decoded.uid,role:roleOf(snap.data()?.role),user:snap.data()||{}}}
async function student(id:string){for(const c of ['individualStudents','students']){const s=await adminDb.collection(c).doc(id).get();if(s.exists)return {id:s.id,data:s.data()||{}}}return null}
async function canAccess(c:any,s:any){if(adminRoles.includes(c.role))return true;if(staffRoles.includes(c.role))return [s.data.tutorId,s.data.staffId,s.data.assignedTutorId,s.data.assignedStaffId,s.data.instructorId].map(String).includes(c.uid);if(c.role==='STUDENT')return String(s.data.firebaseUid||s.data.userId||'')===c.uid||String(c.user.studentDocId||'')===s.id;if(c.role==='PARENT')return String(s.data.parentId||'')===c.uid;if(c.role==='SCHOOL')return String(s.data.schoolId||'')===String(c.user.schoolId||c.uid);return false}
export const handler:Handler=async event=>{try{const c=await caller(event);if(!['GET','POST'].includes(event.httpMethod||''))return json(405,{error:'Method Not Allowed'});
 if(event.httpMethod==='GET'){const q=event.queryStringParameters||{};const sid=String(q.studentId||'');if(!sid)return json(400,{error:'studentId is required.'});const s=await student(sid);if(!s||!(await canAccess(c,s)))return json(403,{error:'You do not have access to this learner.'});let snap=await adminDb.collection('academic_assessments').where('studentId','==',sid).limit(100).get();let records=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a:any,b:any)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')));return json(200,{records});}
 const body=JSON.parse(event.body||'{}');const sid=String(body.studentId||'');const s=await student(sid);if(!s||!staffRoles.includes(c.role)||!(await canAccess(c,s)))return json(403,{error:'Only the learner’s assigned teaching staff can manage assessments.'});
 const title=String(body.title||'').trim();if(!title)return json(400,{error:'Assessment title is required.'});const score=body.score===null||body.score===undefined||body.score===''?null:Number(body.score);if(score!==null&&(!Number.isFinite(score)||score<0||score>100))return json(400,{error:'Score must be between 0 and 100.'});const payload={studentId:sid,title,subject:String(body.subject||'').trim(),assessmentType:String(body.assessmentType||'OTHER').trim(),score,feedback:String(body.feedback||'').trim(),assessedBy:c.uid,updatedAt:FieldValue.serverTimestamp(),createdAt:FieldValue.serverTimestamp()};const ref=body.id?adminDb.collection('academic_assessments').doc(String(body.id)):adminDb.collection('academic_assessments').doc();if(body.id){const old=await ref.get();if(!old.exists||String(old.data()?.studentId)!==sid)return json(404,{error:'Assessment not found.'});await ref.set(payload,{merge:true})}else await ref.set(payload);await adminDb.collection('notifications').add({recipientId:String(s.data.firebaseUid||s.data.userId||''),type:'assessment_update',title:'Assessment updated',message:`${title}${score===null?' has been recorded.':` was recorded at ${score}/100.`}`,link:'/portal/student/assessments',timestamp:FieldValue.serverTimestamp(),read:false});return json(200,{assessment:{id:ref.id,...payload}});
 }catch(e){if(e instanceof Error&&e.message==='AUTH')return json(401,{error:'Authentication required.'});if(e instanceof Error&&e.message==='PROFILE')return json(403,{error:'Portal profile not found.'});console.error('Academic assessments error',e);return json(500,{error:'Unable to process the assessment.'})}};
