import React, { useEffect, useMemo, useState } from 'react';
import { Clock, Edit3, Loader2, Save, Umbrella, X, XCircle } from 'lucide-react';
import { auth, db } from '../../lib/firebase';
import { collection, doc, getDocs, serverTimestamp, updateDoc, writeBatch } from 'firebase/firestore';
import { useToast } from '../../contexts/ToastContext';
import { getEffectiveAuth } from '../../utils/impersonation';

type Schedule={id:string;date:string;startTime?:string;endTime?:string;title?:string;programName?:string;studentId?:string;studentName?:string;tutorId?:string;tutorName?:string;meetingLink?:string;status?:string;schoolName?:string;};
const monday=(date:string)=>{const d=new Date(`${date}T12:00:00`),n=d.getDay();d.setDate(d.getDate()+(n===0?-6:1-n));return d.toISOString().slice(0,10)};
const label=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString('en-NG',{weekday:'long',day:'numeric',month:'short'});
interface Props{tutorId?:string;tutorName?:string;assignedSchools?:any[];assignedStudents?:any[];}
export const StaffClassSchedulesManager:React.FC<Props>=({tutorId,tutorName})=>{
 const {toast}=useToast(),effective=getEffectiveAuth();const [rows,setRows]=useState<Schedule[]>([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Schedule|null>(null),[form,setForm]=useState({date:'',startTime:'',endTime:'',title:'',meetingLink:''}),[saving,setSaving]=useState(false),[holidayWeek,setHolidayWeek]=useState<string|null>(null),[holidayReason,setHolidayReason]=useState('Tutor holiday / no classes this week');
 const load=async()=>{setLoading(true);try{const user=auth.currentUser;const token=user?await user.getIdToken():'';let list:Schedule[]=[];try{const r=await fetch('/.netlify/functions/class-schedules',{headers:token?{Authorization:`Bearer ${token}`}:{}});if(r.ok)list=(await r.json()).schedules||[]}catch{}if(!list.length){const snap=await getDocs(collection(db,'classSchedules'));list=snap.docs.map(d=>({id:d.id,...d.data()} as Schedule))}const uid=tutorId||effective.effectiveUid||user?.uid,name=(tutorName||effective.effectiveName||user?.displayName||'').toLowerCase();setRows(list.filter(s=>(!!uid&&s.tutorId===uid)||((!!name&&!!s.tutorName)&&s.tutorName!.toLowerCase()===name)))}catch(e){console.warn('Tutor schedules failed:',e);setRows([])}finally{setLoading(false)}};
 useEffect(()=>{void load()},[tutorId,tutorName,effective.effectiveUid,effective.effectiveName]);
 const weeks=useMemo(()=>{const map=new Map<string,Schedule[]>();rows.slice().sort((a,b)=>a.date.localeCompare(b.date)||String(a.startTime).localeCompare(String(b.startTime))).forEach(r=>{const w=monday(r.date);if(!map.has(w))map.set(w,[]);map.get(w)!.push(r)});return Array.from(map.entries())},[rows]);
 const openEdit=(r:Schedule)=>{setEditing(r);setForm({date:r.date,startTime:r.startTime||'',endTime:r.endTime||'',title:r.title||'',meetingLink:r.meetingLink||''})};
 const saveEdit=async(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;setSaving(true);try{if(!form.date||!form.startTime||!form.endTime||form.endTime<=form.startTime)throw new Error('Please provide a valid date and time range.');await updateDoc(doc(db,'classSchedules',editing.id),{date:form.date,dayOfWeek:new Date(`${form.date}T12:00:00`).toLocaleDateString('en-US',{weekday:'long'}),startTime:form.startTime,endTime:form.endTime,title:form.title.trim()||editing.title||'Class session',meetingLink:form.meetingLink.trim(),updatedAt:serverTimestamp(),editedBy:effective.effectiveUid||auth.currentUser?.uid||null});toast.success('Class session updated.');setEditing(null);await load()}catch(e:any){toast.error(e.message||'Unable to update class session.')}finally{setSaving(false)}};
 const markWeekHoliday=async()=>{if(!holidayWeek)return;const ids=rows.filter(r=>monday(r.date)===holidayWeek&&!['COMPLETED','ABSENT'].includes(String(r.status||'').toUpperCase())).map(r=>r.id);if(!ids.length){toast.info('There are no active sessions in that week.');setHolidayWeek(null);return}try{const batch=writeBatch(db);ids.forEach(id=>batch.update(doc(db,'classSchedules',id),{status:'CANCELLED',cancellationReason:holidayReason.trim()||'Tutor holiday / no classes this week',holidayWeek:true,updatedAt:serverTimestamp()}));await batch.commit();toast.success('The selected week has been marked as a holiday.');setHolidayWeek(null);await load()}catch(e:any){toast.error(e.message||'Unable to mark the week as a holiday.')}};
 return <div className="space-y-4">{loading?<div className="min-h-40 grid place-items-center text-sm text-slate-500"><Loader2 className="animate-spin mr-2 inline" size={18}/> Loading your classes…</div>:!weeks.length?<div className="rounded-2xl border border-dashed p-8 text-center text-sm text-slate-500">No classes are currently assigned to you.</div>:weeks.map(([week,weekRows])=><section key={week} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden"><div className="p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 dark:border-slate-800"><div><p className="text-[10px] uppercase tracking-wider font-black text-brand-red">Teaching week</p><h3 className="text-sm font-black">Week of {label(week)}</h3><p className="text-[11px] text-slate-500">{weekRows.length} scheduled session{weekRows.length===1?'':'s'}</p></div><button type="button" onClick={()=>setHolidayWeek(week)} className="inline-flex items-center gap-1.5 rounded-xl border border-amber-200 text-amber-700 px-3 py-2 text-[11px] font-black"><Umbrella size={13}/> Mark week as holiday</button></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{weekRows.map(r=><div key={r.id} className="p-4 flex flex-col lg:flex-row lg:items-center gap-3"><div className="lg:w-40 shrink-0"><p className="text-xs font-black">{label(r.date)}</p><p className="text-[11px] text-slate-500 flex items-center gap-1"><Clock size={12}/> {r.startTime} – {r.endTime}</p></div><div className="flex-1 min-w-0"><p className="text-sm font-black truncate">{r.title||r.programName||'Class session'}</p><p className="text-[11px] text-slate-500">{r.studentName||r.programName||'Student class'} · {r.status||'SCHEDULED'}</p></div><button type="button" onClick={()=>openEdit(r)} className="inline-flex items-center justify-center gap-1.5 rounded-xl border px-3 py-2 text-[11px] font-black"><Edit3 size={13}/> Edit session</button></div>)}</div></section>)}
 {editing&&<div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4"><form onSubmit={saveEdit} className="w-full max-w-lg rounded-3xl bg-white dark:bg-slate-900 p-6 space-y-4"><div className="flex items-center justify-between"><div><h3 className="text-base font-black">Edit class session</h3><p className="text-xs text-slate-500">Changes apply to this session only.</p></div><button type="button" onClick={()=>setEditing(null)}><X size={18}/></button></div><input type="text" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Session title" className="w-full rounded-xl border px-3 py-2.5 text-sm"/><div className="grid grid-cols-3 gap-2"><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"/><input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"/><input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"/></div><input type="url" value={form.meetingLink} onChange={e=>setForm({...form,meetingLink:e.target.value})} placeholder="Meeting link" className="w-full rounded-xl border px-3 py-2.5 text-sm"/><button disabled={saving} className="w-full rounded-xl bg-brand-red text-white py-2.5 text-xs font-black inline-flex items-center justify-center gap-2">{saving?<Loader2 size={14} className="animate-spin"/>:<Save size={14}/>} Save changes</button></form></div>}
 {holidayWeek&&<div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4"><div className="w-full max-w-md rounded-3xl bg-white dark:bg-slate-900 p-6 space-y-4"><div className="flex items-center justify-between"><h3 className="text-base font-black">Mark week as holiday</h3><button onClick={()=>setHolidayWeek(null)}><XCircle size={18}/></button></div><p className="text-xs text-slate-500">All active sessions in this teaching week will be marked cancelled with the holiday reason. Individual sessions can still be edited later.</p><textarea value={holidayReason} onChange={e=>setHolidayReason(e.target.value)} className="w-full rounded-xl border p-3 text-sm" rows={3}/><button onClick={()=>void markWeekHoliday()} className="w-full rounded-xl bg-slate-900 text-white py-2.5 text-xs font-black">Confirm holiday week</button></div></div>}</div>;
};
export default StaffClassSchedulesManager;
