import React,{useEffect,useMemo,useState}from'react';
import {AlertCircle,CheckCircle2,ClipboardCheck,Loader2,Save,UserRound}from'lucide-react';
import {auth}from'../../lib/firebase';import SEO from'../../components/ui/SEO';import {DashboardGreeting}from'../../components/portal/DashboardGreeting';
const api=async(path:string,options:RequestInit={})=>{const u=auth.currentUser;if(!u)throw new Error('Please sign in again.');const t=await u.getIdToken();const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`,...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d};
const AssessmentCenter:React.FC<{role:'student'|'parent'|'staff'|'school'}>=({role})=>{const[students,setStudents]=useState<any[]>([]),[selected,setSelected]=useState(''),[records,setRecords]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');const[form,setForm]=useState({title:'',subject:'',assessmentType:'QUIZ',score:'',feedback:''});
useEffect(()=>{(async()=>{try{const d=await api('/api/academic-students');const list=d.students||[];setStudents(list);if(role==='student'&&list[0])setSelected(list[0].id);if(role!=='student'&&list[0])setSelected(list[0].id)}catch(e){setError(e instanceof Error?e.message:'Unable to load learners.')}finally{setLoading(false)}})()},[role]);
useEffect(()=>{if(!selected)return;setError('');api(`/api/academic-assessments?studentId=${encodeURIComponent(selected)}`).then(d=>setRecords(d.records||[])).catch(e=>setError(e instanceof Error?e.message:'Unable to load assessments.'))},[selected]);
const learner=useMemo(()=>students.find(s=>s.id===selected),[students,selected]);const average=useMemo(()=>{const x=records.filter(r=>typeof r.score==='number');return x.length?Math.round(x.reduce((a,r)=>a+r.score,0)/x.length):null},[records]);
const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{await api('/api/academic-assessments',{method:'POST',body:JSON.stringify({studentId:selected,...form,score:form.score})});setForm({title:'',subject:'',assessmentType:'QUIZ',score:'',feedback:''});const d=await api(`/api/academic-assessments?studentId=${encodeURIComponent(selected)}`);setRecords(d.records||[]);setSuccess('Assessment saved.');}catch(e){setError(e instanceof Error?e.message:'Unable to save assessment.')}finally{setSaving(false)}};
if(loading)return <div className="py-12 flex justify-center text-sm text-slate-500"><Loader2 className="animate-spin mr-2" size={18}/>Loading assessments…</div>;
return <div className="space-y-6"><SEO title="Assessments | Jaystarbliss Studios" description="Academic assessment records." noindex/><DashboardGreeting name={role==='staff'?'Assessment workspace':role==='student'?'My assessments':role==='parent'?'Child assessments':'School assessments'} role={role==='staff'?'Teaching staff':role==='student'?'Student':role==='parent'?'Parent':'School'} subtitle="Keep assessment results, scores and feedback in one place."/>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800 flex gap-2"><AlertCircle size={18}/>{error}</div>}{success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800 flex gap-2"><CheckCircle2 size={18}/>{success}</div>}
<div className="pro-surface rounded-2xl p-4"><label className="text-xs font-bold block mb-2">{role==='student'?'Learner':'Learner record'}</label><select className="input" value={selected} onChange={e=>setSelected(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.fullName}</option>)}</select></div>
{learner&&<div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div className="pro-surface rounded-2xl p-5"><UserRound size={18}/><p className="text-xs text-slate-500 mt-2">Learner</p><p className="font-black mt-1">{learner.fullName}</p></div><div className="pro-surface rounded-2xl p-5"><ClipboardCheck size={18}/><p className="text-xs text-slate-500 mt-2">Recorded assessments</p><p className="text-2xl font-black mt-1">{records.length}</p></div><div className="pro-surface rounded-2xl p-5"><CheckCircle2 size={18}/><p className="text-xs text-slate-500 mt-2">Average score</p><p className="text-2xl font-black mt-1">{average===null?'—':`${average}/100`}</p></div></div>}
<div className="grid grid-cols-1 lg:grid-cols-2 gap-6">{role==='staff'&&<form onSubmit={save} className="pro-surface rounded-3xl p-6 space-y-4"><h2 className="font-black text-lg">Record assessment</h2><input required className="input" placeholder="Assessment title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input className="input" placeholder="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><select className="input" value={form.assessmentType} onChange={e=>setForm({...form,assessmentType:e.target.value})}><option value="QUIZ">Quiz</option><option value="ASSIGNMENT">Assignment</option><option value="EXAM">Exam</option><option value="PRACTICAL">Practical</option><option value="PROJECT">Project</option><option value="OTHER">Other</option></select><input required type="number" min="0" max="100" className="input" placeholder="Score / 100" value={form.score} onChange={e=>setForm({...form,score:e.target.value})}/><textarea className="input" rows={4} placeholder="Feedback for the learner" value={form.feedback} onChange={e=>setForm({...form,feedback:e.target.value})}/><button disabled={saving||!selected} className="btn-primary"><Save size={16}/>{saving?'Saving…':'Save assessment'}</button></form>}
<section className="pro-surface rounded-3xl p-6"><h2 className="font-black text-lg mb-4">Assessment history</h2>{!records.length?<div className="py-12 text-center text-sm text-slate-500">No assessment results have been recorded yet.</div>:<div className="space-y-3">{records.map(r=><article key={r.id} className="rounded-2xl border border-slate-200 dark:border-slate-800 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{r.title}</h3><p className="text-xs text-slate-500 mt-1">{r.subject||'General'} • {String(r.assessmentType||'OTHER').replace('_',' ')}</p></div><span className="font-black text-brand-red">{typeof r.score==='number'?`${r.score}/100`:'Pending'}</span></div>{r.feedback&&<p className="text-sm text-slate-600 dark:text-slate-300 mt-3">{r.feedback}</p>}</article>)}</div>}</section></div></div>};export default AssessmentCenter;
