import React, { useEffect, useMemo, useState } from 'react';
import { Banknote, CalendarDays, CheckCircle2, CreditCard, Download, FileText, GraduationCap, KeyRound, Loader2, RefreshCw, ShieldCheck, Wallet, X } from 'lucide-react';
import jsPDF from 'jspdf';
import { billingGet, billingPost, dateLabel, feeFromBase, formatNaira } from '../../lib/billing';
import { useToast } from '../../contexts/ToastContext';
import SEO from '../../components/ui/SEO';

export type BillingCenterRole = 'student' | 'parent' | 'staff' | 'school';
type PaymentRecord = Record<string, any> & { id: string };
type Plan = { id: string; name: string; baseAmount: number; durationWeeks: number; teachingModes: string[]; description: string; active: boolean; role: string };

const dueDateFor = (payment?: PaymentRecord) => {
  if (!payment?.paidAt) return null;
  const date = new Date(payment.paidAt);
  date.setDate(date.getDate() + Number(payment.durationWeeks || 4) * 7);
  return date;
};

const PaymentTable: React.FC<{ payments: PaymentRecord[]; onReceipt: (p: PaymentRecord) => void }> = ({ payments, onReceipt }) => (
  <div className="overflow-x-auto"><table className="min-w-[1040px] w-full text-left text-xs"><thead><tr className="border-b border-slate-200 dark:border-slate-800"><th className="px-3 py-3">Date</th><th className="px-3 py-3">Plan / Child</th><th className="px-3 py-3">Teaching mode</th><th className="px-3 py-3">Duration</th><th className="px-3 py-3">Base</th><th className="px-3 py-3">Fee</th><th className="px-3 py-3">Total</th><th className="px-3 py-3">Reference</th><th className="px-3 py-3"></th></tr></thead><tbody>{payments.map(payment => <tr key={payment.id} className="border-b border-slate-100 dark:border-slate-800/70"><td className="px-3 py-4 whitespace-nowrap">{dateLabel(payment.paidAt || payment.createdAt)}</td><td className="px-3 py-4"><div className="font-bold">{payment.plan || 'Payment'}</div><div className="text-slate-500">{payment.studentName || 'Account payment'}</div></td><td className="px-3 py-4">{payment.teachingMode || 'Standard delivery'}</td><td className="px-3 py-4">{payment.durationWeeks || 4} weeks</td><td className="px-3 py-4">{formatNaira(payment.baseAmount || 0)}</td><td className="px-3 py-4">{formatNaira(payment.transactionFee || 0)}</td><td className="px-3 py-4 font-black">{formatNaira(payment.customerTotal || Number(payment.amount || 0) / 100)}</td><td className="px-3 py-4 font-mono text-[10px]">{payment.reference || payment.id}</td><td className="px-3 py-4"><button type="button" onClick={() => onReceipt(payment)} className="min-h-10 rounded-lg border border-slate-200 px-3 font-bold">Receipt</button></td></tr>)}</tbody></table></div>
);

const AccessPack: React.FC<{ student: Record<string, any> }> = ({ student }) => {
  const [busy, setBusy] = useState(false);
  const name = String(student.fullName || student.studentName || 'Student');
  const username = String(student.username || '');
  const code = String(student.accessCode || student.passcode || '');
  const portal = `${window.location.origin}/portal`;
  const exportText = `JAYSTARBLISS STUDIOS\nSTUDENT PORTAL ACCESS\n\nStudent: ${name}\nUsername: ${username}\nAccess Code: ${code}\nPortal: ${portal}\n\nKeep these details private.`;
  const downloadTxt = () => { const blob = new Blob([exportText], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-student-access.txt`; anchor.click(); URL.revokeObjectURL(url); };
  const downloadPdf = () => { const pdf = new jsPDF(); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(18); pdf.text('JAYSTARBLISS STUDIOS', 20, 24); pdf.setFontSize(13); pdf.text('Student Portal Access', 20, 35); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); [`Student: ${name}`, `Username: ${username || 'Issued by tutor/admin'}`, `Access code: ${code || 'Not issued yet'}`, `Portal: ${portal}`].forEach((line, index) => pdf.text(line, 20, 55 + index * 10)); pdf.text('Keep this document private and share it only with the assigned student.', 20, 105); pdf.save(`${name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-student-access.pdf`); };
  const downloadImage = async () => { setBusy(true); try { const canvas = document.createElement('canvas'); canvas.width = 1200; canvas.height = 700; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Canvas unavailable'); ctx.fillStyle = '#ffffff'; ctx.fillRect(0, 0, canvas.width, canvas.height); ctx.fillStyle = '#1E293B'; ctx.fillRect(0, 0, canvas.width, 130); ctx.fillStyle = '#ffffff'; ctx.font = '700 42px Arial'; ctx.fillText('JAYSTARBLISS STUDIOS', 60, 80); ctx.fillStyle = '#1E293B'; ctx.font = '700 30px Arial'; ctx.fillText('Student Portal Access', 60, 195); ctx.font = '600 26px Arial'; ctx.fillText(`Student: ${name}`, 60, 270); ctx.font = '26px Arial'; ctx.fillText(`Username: ${username || 'Issued by tutor/admin'}`, 60, 330); ctx.fillText(`Access Code: ${code || 'Not issued yet'}`, 60, 390); ctx.fillText(`Portal: ${portal}`, 60, 450); ctx.font = '20px Arial'; ctx.fillStyle = '#64748B'; ctx.fillText('Keep these details private.', 60, 540); const blob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, 'image/png')); if (!blob) throw new Error('Unable to create image'); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-student-access.png`; anchor.click(); URL.revokeObjectURL(url); } finally { setBusy(false); } };
  if (!code && !username) return <span className="text-xs text-slate-400">Access pack not issued</span>;
  return <div className="flex flex-wrap gap-2"><button type="button" onClick={downloadTxt} className="min-h-10 inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-xs font-bold"><Download size={13}/>TXT</button><button type="button" onClick={downloadPdf} className="min-h-10 inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-xs font-bold"><FileText size={13}/>PDF</button><button type="button" disabled={busy} onClick={downloadImage} className="min-h-10 inline-flex items-center gap-1.5 rounded-lg bg-brand-slate px-3 text-xs font-bold text-white">{busy ? <Loader2 size={13} className="animate-spin"/> : <Download size={13}/>}Image</button></div>;
};

const BillingCenter: React.FC<{ role: BillingCenterRole }> = ({ role }) => {
  const { toast } = useToast();
  const [data, setData] = useState<any>({ payments: [], enrollments: [], students: [], withdrawals: [], wallet: {}, config: { plans: {}, parentFeePolicy: {}, schoolFeePolicy: {} } });
  const [loading, setLoading] = useState(true);
  const [selectedStudentId, setSelectedStudentId] = useState('');
  const [selectedPlanId, setSelectedPlanId] = useState('');
  const [teachingMode, setTeachingMode] = useState('');
  const [paymentMethod, setPaymentMethod] = useState<'card' | 'bank_transfer'>('card');
  const [showCheckout, setShowCheckout] = useState(false);
  const [withdrawing, setWithdrawing] = useState(false);
  const [withdrawalAmount, setWithdrawalAmount] = useState('');
  const [banks, setBanks] = useState<any[]>([]);
  const [bankCode, setBankCode] = useState('');
  const [accountNumber, setAccountNumber] = useState('');
  const [savingBank, setSavingBank] = useState(false);

  const load = async () => { setLoading(true); try { setData(await billingGet<any>('billing-data')); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load billing data.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (role === 'staff') billingGet<any>('paystack-banks').then(result => setBanks(result.banks || [])).catch(() => undefined); }, [role]);
  useEffect(() => { const reference = new URLSearchParams(window.location.search).get('reference'); if (!reference) return; billingPost<any>('paystack-verify', { reference }).then(() => { toast.success('Payment verified successfully.'); window.history.replaceState({}, document.title, window.location.pathname); void load(); }).catch(error => toast.error(error instanceof Error ? error.message : 'Payment verification failed.')); }, []);

  const plans = useMemo(() => Object.values((data.config?.plans || {}) as Record<string, Plan>).filter(p => p && p.active && ((role === 'school' && p.role === 'school') || (role !== 'school' && p.role !== 'school'))), [data.config, role]);
  const selectedPlan = plans.find(p => p.id === selectedPlanId);
  const feePolicy = role === 'school' ? data.config?.schoolFeePolicy : data.config?.parentFeePolicy;
  const charge = selectedPlan ? feeFromBase(selectedPlan.baseAmount, feePolicy) : null;
  const paidPayments = (data.payments || []).filter((p: PaymentRecord) => String(p.status || '').toUpperCase() === 'PAID').sort((a: PaymentRecord, b: PaymentRecord) => new Date(b.paidAt || b.createdAt || 0).getTime() - new Date(a.paidAt || a.createdAt || 0).getTime());
  const dueDate = dueDateFor(paidPayments[0]);

  const startCheckout = (planId?: string, studentId?: string) => { const nextPlanId = planId || selectedPlanId || plans[0]?.id || ''; setSelectedPlanId(nextPlanId); setSelectedStudentId(studentId || selectedStudentId || (data.students?.[0]?.id || '')); const plan = plans.find(p => p.id === nextPlanId); setTeachingMode(plan?.teachingModes?.[0] || 'Standard delivery'); setShowCheckout(true); };
  const processPayment = async (event: React.FormEvent) => { event.preventDefault(); if (!selectedPlan) return; if (role === 'parent' && !selectedStudentId) { toast.error('Select the child this payment is for.'); return; } try { const result = await billingPost<any>('paystack-initialize', { planId: selectedPlan.id, role, studentId: selectedStudentId || undefined, teachingMode, durationWeeks: role === 'school' ? selectedPlan.durationWeeks : 4, paymentMethod }); window.location.assign(result.authorizationUrl); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to start payment.'); } };
  const receipt = (payment: PaymentRecord) => { const pdf = new jsPDF(); const paidAt = payment.paidAt ? new Date(payment.paidAt) : new Date(); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(18); pdf.text('JAYSTARBLISS STUDIOS', 20, 24); pdf.setFontSize(13); pdf.text('Official Payment Receipt', 20, 35); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); [`Reference: ${payment.reference || payment.id}`, `Date paid: ${paidAt.toLocaleString('en-NG')}`, `Child / Student: ${payment.studentName || 'Account'}`, `Plan: ${payment.plan || 'Payment'}`, `Teaching mode: ${payment.teachingMode || 'Standard delivery'}`, `Duration: ${payment.durationWeeks || 4} weeks`, `Base fee: ${formatNaira(payment.baseAmount)}`, `Transaction fee: ${formatNaira(payment.transactionFee)}`, `Total paid: ${formatNaira(payment.customerTotal || Number(payment.amount || 0) / 100)}`, `Payment method: ${payment.paymentMethod || 'Paystack'}`].forEach((line, index) => pdf.text(line, 20, 55 + index * 10)); pdf.save(`jaystarbliss-receipt-${payment.reference || payment.id}.pdf`); };
  const saveBank = async (event: React.FormEvent) => { event.preventDefault(); setSavingBank(true); try { await billingPost('wallet-withdraw', { action: 'save_bank', bankCode, accountNumber }); toast.success('Verified bank account saved.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to verify bank account.'); } finally { setSavingBank(false); } };
  const withdraw = async (event: React.FormEvent) => { event.preventDefault(); setWithdrawing(true); try { const result = await billingPost<any>('wallet-withdraw', { action: 'withdraw', amount: Number(withdrawalAmount) }); toast.success(`Withdrawal submitted: ${result.status || 'PROCESSING'}`); setWithdrawalAmount(''); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to submit withdrawal.'); } finally { setWithdrawing(false); } };

  if (loading) return <div className="py-10 flex justify-center text-sm text-slate-500"><Loader2 className="animate-spin mr-2" size={18}/>Loading billing workspace...</div>;
  return <section className="space-y-6" aria-label="Billing center"><SEO title="Billing Center | Jaystarbliss Studios" description="Payments, plans, receipts and staff wallet." noindex={true}/>
    <div className="pro-surface rounded-3xl p-6 md:p-8"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="text-brand-red text-xs font-black uppercase tracking-widest flex items-center gap-2"><ShieldCheck size={14}/> Billing Center</div><h2 className="text-2xl font-black mt-2">{role === 'staff' ? 'Wallet & assigned student billing' : role === 'school' ? 'School billing & partnership' : 'Plans, payments & due dates'}</h2><p className="text-sm text-slate-500 mt-1">Every verified payment carries its plan, mode, student, duration, fee and gateway reference.</p></div><button type="button" onClick={() => void load()} className="min-h-11 inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-xs font-bold"><RefreshCw size={14}/>Refresh</button></div></div>
    {role !== 'staff' && <div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div className="pro-surface rounded-2xl p-5"><p className="text-xs text-slate-500">Latest payment</p><p className="text-xl font-black mt-1">{paidPayments[0] ? formatNaira(paidPayments[0].customerTotal || Number(paidPayments[0].amount || 0) / 100) : '—'}</p><p className="text-xs text-slate-500 mt-1">{paidPayments[0] ? dateLabel(paidPayments[0].paidAt) : 'No verified payments yet'}</p></div><div className="pro-surface rounded-2xl p-5"><p className="text-xs text-slate-500">Paid through</p><p className="text-xl font-black mt-1">{dueDate ? dueDate.toLocaleDateString('en-NG') : '—'}</p><p className="text-xs text-slate-500 mt-1">{role === 'school' ? 'Based on the package duration' : '28 days from the last paid date'}</p></div><div className="pro-surface rounded-2xl p-5"><p className="text-xs text-slate-500">Transactions</p><p className="text-xl font-black mt-1">{paidPayments.length}</p><p className="text-xs text-slate-500 mt-1">Verified on this account</p></div></div>}
    {role === 'staff' && <><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><div className="pro-surface rounded-2xl p-5"><Wallet className="text-brand-red" size={20}/><p className="text-xs text-slate-500 mt-3">Available balance</p><p className="text-2xl font-black">{formatNaira(data.wallet?.availableBalance)}</p></div><div className="pro-surface rounded-2xl p-5"><Banknote size={20}/><p className="text-xs text-slate-500 mt-3">Reserved</p><p className="text-2xl font-black">{formatNaira(data.wallet?.reservedBalance)}</p></div><div className="pro-surface rounded-2xl p-5"><GraduationCap size={20}/><p className="text-xs text-slate-500 mt-3">Lifetime earned</p><p className="text-2xl font-black">{formatNaira(data.wallet?.lifetimeEarned)}</p></div></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><form onSubmit={saveBank} className="pro-surface rounded-2xl p-6 space-y-4"><div><h3 className="font-black">Verified payout account</h3><p className="text-xs text-slate-500 mt-1">Only the final four digits are shown after verification.</p></div><select required value={bankCode} onChange={e => setBankCode(e.target.value)} className="w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-white dark:bg-slate-900"><option value="">Select bank</option>{banks.map(bank => <option key={bank.code} value={bank.code}>{bank.name}</option>)}</select><input required inputMode="numeric" maxLength={10} value={accountNumber} onChange={e => setAccountNumber(e.target.value.replace(/\D/g, '').slice(0, 10))} placeholder="10-digit account number" className="w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-transparent"/><button disabled={savingBank} className="min-h-11 rounded-xl bg-brand-slate text-white px-4 text-xs font-bold">{savingBank ? 'Verifying…' : 'Verify & save account'}</button>{data.wallet?.bankDetailsVerified && <p className="text-xs text-green-700 flex items-center gap-1"><CheckCircle2 size={14}/> Verified account •••• {data.wallet.bankAccountLast4}</p>}</form><form onSubmit={withdraw} className="pro-surface rounded-2xl p-6 space-y-4"><div><h3 className="font-black">Request withdrawal</h3><p className="text-xs text-slate-500 mt-1">Minimum: {formatNaira(data.config?.minimumWithdrawalAmount || 10000)}. Funds are reserved until Paystack confirms the transfer.</p></div><input required type="number" min={data.config?.minimumWithdrawalAmount || 10000} step="100" value={withdrawalAmount} onChange={e => setWithdrawalAmount(e.target.value)} placeholder="Amount in naira" className="w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-transparent"/><button disabled={withdrawing} className="min-h-11 rounded-xl bg-brand-red text-white px-4 text-xs font-bold">{withdrawing ? 'Submitting…' : 'Withdraw to verified bank'}</button></form></div></>}
    {role !== 'staff' && <div className="pro-surface rounded-2xl p-6"><div className="flex items-center justify-between gap-3 mb-5"><div><h3 className="font-black">Start a payment</h3><p className="text-xs text-slate-500 mt-1">Review the base fee and pass-through transaction fee before Paystack opens.</p></div><CreditCard size={20} className="text-brand-red"/></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{plans.map(plan => <button type="button" key={plan.id} onClick={() => startCheckout(plan.id)} className="text-left rounded-2xl border border-slate-200 dark:border-slate-800 p-4 hover:border-brand-red transition-colors"><div className="font-black">{plan.name}</div><div className="text-2xl font-black mt-2">{formatNaira(plan.baseAmount)}</div><div className="text-xs text-slate-500">{plan.durationWeeks} weeks</div><div className="mt-3 text-xs text-brand-red font-bold">Continue to payment →</div></button>)}</div></div>}
    {(role === 'parent' || role === 'school') && data.students?.length > 0 && <div className="pro-surface rounded-2xl p-6"><h3 className="font-black mb-4">{role === 'parent' ? 'Children' : 'School students'}</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{data.students.map((student: any) => <div key={`${student.id}-${student.email || ''}`} className="rounded-2xl border border-slate-200 dark:border-slate-800 p-4"><div className="flex items-center justify-between"><div><div className="font-black">{student.fullName || student.studentName}</div><div className="text-xs text-slate-500">{student.grade || student.class || 'Cadet'} • {student.plan || 'Learning track'}</div></div><GraduationCap size={20} className="text-brand-red"/></div>{role === 'parent' && <button type="button" onClick={() => startCheckout(undefined, student.id)} className="min-h-10 mt-4 rounded-lg bg-brand-slate text-white px-3 text-xs font-bold">Pay for student</button>}</div>)}</div></div>}
    {role === 'staff' && <div className="pro-surface rounded-2xl p-6"><div className="flex items-center justify-between mb-5"><div><h3 className="font-black">Assigned students & paid plan context</h3><p className="text-xs text-slate-500">Only students explicitly assigned to this staff account are listed.</p></div><KeyRound size={20} className="text-brand-red"/></div><div className="space-y-4">{(data.students || []).length === 0 ? <div className="py-8 text-sm text-slate-500 text-center">No students assigned.</div> : data.students.map((student: any) => { const payment = (data.payments || []).find((p: any) => p.studentId === student.id); return <div key={`${student.id}-${student.email || ''}`} className="rounded-2xl border border-slate-200 dark:border-slate-800 p-5"><div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><h4 className="font-black">{student.fullName || student.studentName || 'Student'}</h4><p className="text-xs text-slate-500 mt-1">{payment?.plan || student.plan || 'Assigned learning track'} • {payment?.teachingMode || student.teachingMode || 'Teaching mode set by admin'}</p><p className="text-xs text-slate-500 mt-1">{payment ? `Paid ${formatNaira(payment.customerTotal || Number(payment.amount || 0) / 100)} on ${dateLabel(payment.paidAt)}` : 'No payment record linked yet'}</p></div><AccessPack student={student}/></div></div>; })}</div></div>}
    <div className="pro-surface rounded-2xl p-6"><div className="flex items-center justify-between mb-5"><div><h3 className="font-black">Payment history</h3><p className="text-xs text-slate-500">Complete verified transaction history with fee breakdown.</p></div><CalendarDays size={20} className="text-brand-red"/></div>{paidPayments.length ? <PaymentTable payments={paidPayments} onReceipt={receipt}/> : <div className="py-10 text-center text-sm text-slate-500">No verified payments yet.</div>}</div>
    {role === 'staff' && (data.withdrawals || []).length > 0 && <div className="pro-surface rounded-2xl p-6"><h3 className="font-black mb-4">Withdrawal history</h3><div className="space-y-2">{data.withdrawals.map((w: any) => <div key={w.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 rounded-xl border border-slate-200 dark:border-slate-800 px-4 py-3 text-xs"><span>{dateLabel(w.createdAt)}</span><span className="font-black">{formatNaira(w.amount)}</span><span>{w.status}</span><span>•••• {w.bankLast4 || '—'}</span></div>)}</div></div>}
    {showCheckout && <div className="fixed inset-0 z-[80] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-lg rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-2xl p-6 relative"><button type="button" onClick={() => setShowCheckout(false)} className="absolute right-4 top-4 min-h-10 min-w-10 rounded-full border border-slate-200 flex items-center justify-center" aria-label="Close payment"><X size={16}/></button><h3 className="text-xl font-black pr-12">Payment summary</h3><p className="text-xs text-slate-500 mt-1">Review exactly what will be sent to Paystack.</p><form onSubmit={processPayment} className="space-y-4 mt-6"><select required value={selectedPlanId} onChange={e => { setSelectedPlanId(e.target.value); const plan = plans.find(p => p.id === e.target.value); setTeachingMode(plan?.teachingModes?.[0] || 'Standard delivery'); }} className="w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-white dark:bg-slate-900">{plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select>{role === 'parent' && <select required value={selectedStudentId} onChange={e => setSelectedStudentId(e.target.value)} className="w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-white dark:bg-slate-900"><option value="">Select child / student</option>{data.students.map((student: any) => <option key={student.id} value={student.id}>{student.fullName || student.studentName}</option>)}</select>}<select value={teachingMode} onChange={e => setTeachingMode(e.target.value)} className="w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-white dark:bg-slate-900">{(selectedPlan?.teachingModes || ['Standard delivery']).map(mode => <option key={mode}>{mode}</option>)}</select><select value={paymentMethod} onChange={e => setPaymentMethod(e.target.value as 'card' | 'bank_transfer')} className="w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-white dark:bg-slate-900"><option value="card">Card</option><option value="bank_transfer">Bank transfer</option></select>{charge && <div className="rounded-2xl bg-slate-50 dark:bg-slate-950 p-4 text-sm space-y-2"><div className="flex justify-between"><span>Base fee</span><strong>{formatNaira(charge.baseAmount)}</strong></div><div className="flex justify-between"><span>Transaction fee</span><strong>{formatNaira(charge.transactionFee)}</strong></div><div className="flex justify-between border-t border-slate-200 dark:border-slate-800 pt-2"><span className="font-black">Total due</span><strong className="text-lg">{formatNaira(charge.totalAmount)}</strong></div><p className="text-[11px] text-slate-500">Transaction fee is added to the service fee and the total is validated again against Paystack before the payment is recorded.</p></div>}<button type="submit" className="w-full min-h-11 rounded-xl bg-brand-red text-white font-bold">Continue to Paystack</button></form></div></div>}
  </section>;
};

export default BillingCenter;
