import React, { useEffect, useMemo, useState } from 'react';
import { Banknote, CalendarDays, CheckCircle2, CreditCard, Download, FileText, Loader2, RefreshCw, ShieldCheck, Wallet, X, Building2, Smartphone } from 'lucide-react';
import jsPDF from 'jspdf';
import { billingGet, billingPost, dateLabel, feeFromBase, formatNaira } from '../../lib/billing';
import { useToast } from '../../contexts/ToastContext';
import SEO from '../../components/ui/SEO';

export type BillingCenterRole = 'student' | 'parent' | 'staff' | 'school';
type PaymentRecord = Record<string, any> & { id: string };
type Plan = { id: string; name: string; baseAmount: number; durationWeeks: number; teachingModes: string[]; description: string; active: boolean; role: string };
type PaymentMethod = 'card' | 'bank_transfer' | 'opay';

const dueDateFor = (payment?: PaymentRecord) => { if (!payment?.paidAt) return null; const date = new Date(payment.paidAt); date.setDate(date.getDate() + Number(payment.durationWeeks || 4) * 7); return date; };
const methodLabel = (method: PaymentMethod) => method === 'card' ? 'Card' : method === 'bank_transfer' ? 'Bank Transfer' : 'OPay / Mobile Money';

const PaymentTable: React.FC<{ payments: PaymentRecord[]; onReceipt: (p: PaymentRecord) => void }> = ({ payments, onReceipt }) => <div className="overflow-x-auto"><table className="min-w-[1000px] w-full text-left text-xs"><thead><tr className="border-b border-slate-200 dark:border-slate-800">{['Date','Plan / Student','Mode','Duration','Base','Paystack Fee','Customer Total','Reference',''].map(h => <th key={h} className="px-3 py-3 font-black uppercase tracking-wider text-slate-500">{h}</th>)}</tr></thead><tbody>{payments.map(payment => <tr key={payment.id} className="border-b border-slate-100 dark:border-slate-800/70"><td className="px-3 py-4 whitespace-nowrap">{dateLabel(payment.paidAt || payment.createdAt)}</td><td className="px-3 py-4"><div className="font-bold">{payment.plan || 'Payment'}</div><div className="text-slate-500">{payment.studentName || 'Account payment'}</div></td><td className="px-3 py-4">{payment.teachingMode || 'Standard delivery'}</td><td className="px-3 py-4">{payment.durationWeeks || 4} weeks</td><td className="px-3 py-4">{formatNaira(payment.baseAmount || 0)}</td><td className="px-3 py-4">{formatNaira(payment.transactionFee || 0)}</td><td className="px-3 py-4 font-black">{formatNaira(payment.customerTotal || Number(payment.amount || 0) / 100)}</td><td className="px-3 py-4 font-mono text-[10px]">{payment.reference || payment.id}</td><td className="px-3 py-4"><button type="button" onClick={() => onReceipt(payment)} className="min-h-10 rounded-lg border border-slate-200 px-3 font-bold">Receipt</button></td></tr>)}</tbody></table></div>;

const BillingCenter: React.FC<{ role: BillingCenterRole }> = ({ role }) => {
  const { toast } = useToast();
  const [data, setData] = useState<any>({ payments: [], students: [], withdrawals: [], wallet: {}, config: { plans: {}, parentFeePolicy: {}, schoolFeePolicy: {} } });
  const [loading, setLoading] = useState(true); const [selectedStudentId, setSelectedStudentId] = useState(''); const [selectedPlanId, setSelectedPlanId] = useState(''); const [teachingMode, setTeachingMode] = useState(''); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('card'); const [showCheckout, setShowCheckout] = useState(false); const [paying, setPaying] = useState(false); const [notice, setNotice] = useState('');
  const [withdrawalAmount, setWithdrawalAmount] = useState(''); const [bankCode, setBankCode] = useState(''); const [accountNumber, setAccountNumber] = useState(''); const [banks, setBanks] = useState<any[]>([]); const [savingBank, setSavingBank] = useState(false); const [withdrawing, setWithdrawing] = useState(false);

  const load = async () => { setLoading(true); try { setData(await billingGet<any>('billing-data')); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load billing data.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (role === 'staff') billingGet<any>('paystack-banks').then(result => setBanks(result.banks || [])).catch(() => undefined); }, [role]);
  useEffect(() => { const reference = new URLSearchParams(window.location.search).get('reference'); if (!reference) return; billingPost<any>('paystack-verify', { reference }).then(() => { toast.success('Payment verified successfully.'); window.history.replaceState({}, document.title, window.location.pathname); void load(); }).catch(error => toast.error(error instanceof Error ? error.message : 'Payment verification failed.')); }, []);

  const plans = useMemo(() => Object.values((data.config?.plans || {}) as Record<string, Plan>).filter(p => p?.active && ((role === 'school' && p.role === 'school') || (role !== 'school' && p.role !== 'school'))), [data.config, role]);
  const selectedPlan = plans.find(p => p.id === selectedPlanId);
  const feePolicy = role === 'school' ? data.config?.schoolFeePolicy : data.config?.parentFeePolicy;
  const preview = selectedPlan ? feeFromBase(selectedPlan.baseAmount, feePolicy) : null;
  const payments = (data.payments || []).filter((p: PaymentRecord) => String(p.status || '').toUpperCase() === 'PAID').sort((a: PaymentRecord, b: PaymentRecord) => new Date(b.paidAt || b.createdAt || 0).getTime() - new Date(a.paidAt || a.createdAt || 0).getTime());
  const dueDate = dueDateFor(payments[0]);

  const startCheckout = (plan?: Plan, studentId?: string) => { const next = plan || selectedPlan || plans[0]; if (!next) return; setSelectedPlanId(next.id); setSelectedStudentId(studentId || selectedStudentId || data.students?.[0]?.id || ''); setTeachingMode(next.teachingModes?.[0] || 'Standard delivery'); setPaymentMethod('card'); setNotice(''); setShowCheckout(true); };
  const processPayment = async (event: React.FormEvent) => { event.preventDefault(); if (!selectedPlan) return; if (role === 'parent' && !selectedStudentId) { toast.error('Select the child this payment is for.'); return; } setPaying(true); try { const result = await billingPost<any>('paystack-initialize', { planId: selectedPlan.id, role, studentId: selectedStudentId || undefined, teachingMode, durationWeeks: role === 'school' ? selectedPlan.durationWeeks : 4, paymentMethod }); window.location.assign(result.authorizationUrl); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to start payment.'); } finally { setPaying(false); } };
  const receipt = (payment: PaymentRecord) => { const pdf = new jsPDF(); const paidAt = payment.paidAt ? new Date(payment.paidAt) : new Date(); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(18); pdf.text('JAYSTARBLISS STUDIOS', 20, 24); pdf.setFontSize(13); pdf.text('Official Payment Receipt', 20, 35); pdf.setFont('helvetica', 'normal'); pdf.setFontSize(10); [`Reference: ${payment.reference || payment.id}`, `Date paid: ${paidAt.toLocaleString('en-NG')}`, `Student: ${payment.studentName || 'Account'}`, `Plan: ${payment.plan || 'Payment'}`, `Teaching mode: ${payment.teachingMode || 'Standard delivery'}`, `Duration: ${payment.durationWeeks || 4} weeks`, `Base fee: ${formatNaira(payment.baseAmount)}`, `Paystack transaction fee: ${formatNaira(payment.transactionFee)}`, `Customer total: ${formatNaira(payment.customerTotal || Number(payment.amount || 0) / 100)}`, `Payment method: ${payment.paymentMethod || 'Paystack'}`].forEach((line, index) => pdf.text(line, 20, 55 + index * 10)); pdf.save(`jaystarbliss-receipt-${payment.reference || payment.id}.pdf`); };
  const saveBank = async (event: React.FormEvent) => { event.preventDefault(); setSavingBank(true); try { await billingPost('wallet-withdraw', { action: 'save_bank', bankCode, accountNumber }); toast.success('Verified bank account saved.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to verify bank account.'); } finally { setSavingBank(false); } };
  const withdraw = async (event: React.FormEvent) => { event.preventDefault(); setWithdrawing(true); try { await billingPost('wallet-withdraw', { action: 'withdraw', amount: Number(withdrawalAmount) }); toast.success('Withdrawal submitted.'); setWithdrawalAmount(''); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to submit withdrawal.'); } finally { setWithdrawing(false); } };

  if (loading) return <div className="py-12 flex justify-center text-sm text-slate-500"><Loader2 className="animate-spin mr-2" size={18}/>Loading billing workspace…</div>;
  return <section className="space-y-6" aria-label="Billing center"><SEO title="Billing Center | Jaystarbliss Studios" description="Payments, plans, receipts and staff wallet." noindex={true}/>
    <div className="pro-surface rounded-3xl p-6 md:p-8"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-brand-red"><ShieldCheck size={14}/> Billing Center</div><h1 className="mt-2 text-2xl font-black text-slate-900 dark:text-white">{role === 'staff' ? 'Tutor wallet & student billing' : role === 'school' ? 'School billing' : 'Plans & payments'}</h1><p className="mt-1 text-sm text-slate-500">Transparent pricing, Paystack checkout and verified receipts.</p></div><button type="button" onClick={() => void load()} className="min-h-11 inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 text-xs font-bold"><RefreshCw size={14}/>Refresh</button></div></div>
    {role !== 'staff' && <div className="grid grid-cols-1 gap-4 md:grid-cols-3"><div className="pro-surface rounded-2xl p-5"><p className="text-xs text-slate-500">Latest payment</p><p className="mt-1 text-xl font-black">{payments[0] ? formatNaira(payments[0].customerTotal || Number(payments[0].amount || 0) / 100) : '—'}</p><p className="mt-1 text-xs text-slate-500">{payments[0] ? dateLabel(payments[0].paidAt) : 'No verified payment yet'}</p></div><div className="pro-surface rounded-2xl p-5"><p className="text-xs text-slate-500">Paid through</p><p className="mt-1 text-xl font-black">{dueDate ? dueDate.toLocaleDateString('en-NG') : '—'}</p></div><div className="pro-surface rounded-2xl p-5"><p className="text-xs text-slate-500">Verified transactions</p><p className="mt-1 text-xl font-black">{payments.length}</p></div></div>}

    {role !== 'staff' && <div className="pro-surface rounded-3xl p-6 md:p-8"><div className="mb-5"><h2 className="text-xl font-black">Choose a payment plan</h2><p className="mt-1 text-xs text-slate-500">The amount shown as the plan price is the amount sent to Paystack. Paystack adds its transaction fee at checkout.</p></div><div className="grid gap-4 md:grid-cols-2">{plans.map(plan => { const fee = feeFromBase(plan.baseAmount, feePolicy); return <article key={plan.id} className="rounded-2xl border border-slate-200 p-5 dark:border-slate-800"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-slate-900 dark:text-white">{plan.name}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{plan.description}</p></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black dark:bg-slate-800">{plan.durationWeeks} weeks</span></div><div className="mt-5 grid grid-cols-3 gap-2 text-xs"><div><span className="block text-slate-400">Base</span><strong>{formatNaira(plan.baseAmount)}</strong></div><div><span className="block text-slate-400">Est. fee</span><strong>{formatNaira(fee.transactionFee)}</strong></div><div><span className="block text-slate-400">Est. total</span><strong>{formatNaira(fee.totalAmount)}</strong></div></div><button type="button" onClick={() => startCheckout(plan)} className="mt-5 min-h-11 w-full rounded-xl bg-brand-red px-4 text-sm font-black text-white">Continue to payment</button></article>; })}</div></div>}

    {showCheckout && selectedPlan && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl dark:bg-slate-900"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-wider text-brand-red">Payment review</p><h2 className="mt-1 text-xl font-black">{selectedPlan.name}</h2></div><button type="button" onClick={() => setShowCheckout(false)} className="min-h-11 min-w-11 rounded-xl text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><X className="mx-auto" size={19}/></button></div><form onSubmit={processPayment} className="mt-6 space-y-5">
      {role === 'parent' && <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">Student / Child</span><select required value={selectedStudentId} onChange={e => setSelectedStudentId(e.target.value)} className="min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-800"><option value="">Select child</option>{(data.students || []).map((student: any) => <option key={student.id} value={student.id}>{student.fullName || student.studentName || student.username}</option>)}</select></label>}
      <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">Teaching mode</span><select value={teachingMode} onChange={e => setTeachingMode(e.target.value)} className="min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-800">{selectedPlan.teachingModes.map(mode => <option key={mode}>{mode}</option>)}</select></label>
      <div className="rounded-2xl border border-slate-200 dark:border-slate-800"><div className="flex justify-between border-b border-slate-100 px-4 py-3 text-sm dark:border-slate-800"><span>Plan price</span><strong>{formatNaira(selectedPlan.baseAmount)}</strong></div><div className="flex justify-between border-b border-slate-100 px-4 py-3 text-sm dark:border-slate-800"><span>Estimated Paystack fee</span><strong>{formatNaira(preview?.transactionFee || 0)}</strong></div><div className="flex justify-between px-4 py-4 text-base font-black"><span>Estimated customer total</span><strong>{formatNaira(preview?.totalAmount || selectedPlan.baseAmount)}</strong></div></div>
      <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-xs leading-5 text-blue-900 dark:border-blue-900/50 dark:bg-blue-950/30 dark:text-blue-200"><strong>Important:</strong> the estimated fee is shown for transparency only. We send <strong>{formatNaira(selectedPlan.baseAmount)}</strong> — not the gross total — to Paystack. Your selected checkout method will show the actual Paystack fee before you authorize payment. This prevents the fee from being charged twice.</div>
      <div><p className="mb-2 text-xs font-black uppercase tracking-wider text-slate-500">Payment method</p><div className="grid grid-cols-3 gap-2">{(['card','bank_transfer','opay'] as PaymentMethod[]).map(method => <button key={method} type="button" onClick={() => setPaymentMethod(method)} className={`min-h-16 rounded-xl border p-2 text-xs font-bold ${paymentMethod === method ? 'border-brand-red bg-red-50 text-brand-red dark:bg-red-950/20' : 'border-slate-200 dark:border-slate-700'}`}>{method === 'card' ? <CreditCard className="mx-auto mb-1" size={18}/> : method === 'bank_transfer' ? <Building2 className="mx-auto mb-1" size={18}/> : <Smartphone className="mx-auto mb-1" size={18}/>} {methodLabel(method)}</button>)}</div></div>
      {notice && <div className="rounded-xl bg-slate-100 p-3 text-xs text-slate-600">{notice}</div>}<button disabled={paying} type="submit" className="min-h-12 w-full rounded-xl bg-brand-red px-5 text-sm font-black text-white disabled:opacity-50">{paying ? 'Opening Paystack…' : `Proceed with ${methodLabel(paymentMethod)}`}</button></form></div></div>}

    {role === 'staff' && <div className="grid gap-6 lg:grid-cols-2"><div className="pro-surface rounded-3xl p-6"><div className="flex items-center gap-3"><Wallet className="text-brand-red"/><div><h2 className="font-black">Tutor wallet</h2><p className="text-xs text-slate-500">Verified earnings available for withdrawal.</p></div></div><p className="mt-5 text-3xl font-black">{formatNaira(data.wallet?.availableBalance || 0)}</p><form onSubmit={saveBank} className="mt-6 space-y-3"><select required value={bankCode} onChange={e => setBankCode(e.target.value)} className="min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm dark:border-slate-700 dark:bg-slate-800"><option value="">Select bank</option>{banks.map(bank => <option key={bank.code} value={bank.code}>{bank.name}</option>)}</select><input required value={accountNumber} onChange={e => setAccountNumber(e.target.value)} placeholder="10-digit account number" className="min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm dark:border-slate-700 dark:bg-slate-800"/><button disabled={savingBank} className="min-h-11 w-full rounded-xl border border-slate-300 text-xs font-bold">{savingBank ? 'Verifying…' : 'Save / Verify Bank Account'}</button></form><form onSubmit={withdraw} className="mt-5 flex gap-2"><input required type="number" min="1" value={withdrawalAmount} onChange={e => setWithdrawalAmount(e.target.value)} placeholder="Amount" className="min-h-11 min-w-0 flex-1 rounded-xl border border-slate-200 px-3 text-sm dark:border-slate-700 dark:bg-slate-800"/><button disabled={withdrawing} className="min-h-11 rounded-xl bg-brand-red px-4 text-xs font-bold text-white">{withdrawing ? 'Submitting…' : 'Withdraw'}</button></form></div><div className="pro-surface rounded-3xl p-6"><h2 className="font-black">Student payments linked to your work</h2><p className="mt-1 text-xs text-slate-500">Payment records are reconciled against the assigned student and gateway reference.</p><div className="mt-5"><PaymentTable payments={payments} onReceipt={receipt}/></div></div></div>}

    {role !== 'staff' && <div className="pro-surface rounded-3xl p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-black">Payment history</h2><p className="mt-1 text-xs text-slate-500">The fee below is the actual Paystack fee recorded after verification.</p></div><Banknote className="text-brand-red" size={20}/></div>{payments.length ? <PaymentTable payments={payments} onReceipt={receipt}/> : <div className="rounded-2xl border border-dashed border-slate-300 p-10 text-center text-sm text-slate-500">No verified payments yet.</div>}</div>}
  </section>;
};
export default BillingCenter;
