import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Calendar as CalendarIcon, CheckCircle2, CircleAlert, Clock, Edit3, ExternalLink, Loader2, Save, School, Timer, Video, X } from 'lucide-react';
import { auth, db } from '../../lib/firebase';
import { doc, getDoc } from 'firebase/firestore';
import SEO from '../../components/ui/SEO';
import { isStudentClassMatch } from '../../utils/classMatching';

type Status='upcoming'|'ongoing'|'completed'|'absent'|'cancelled'|'rescheduled'|'scheduled';
type Raw={id:string;title?:string;date?:string;startTime?:string;endTime?:string;tutorName?:string;meetingLink?:string;url?:string;schoolId?:string;schoolName?:string;programId?:string;programmeId?:string;programName?:string;programmeName?:string;classLevel?:string;classLevels?:string[];studentId?:string;studentEmail?:string;status?:string; scheduleGroupId?:string};
type Event={id:string;title:string;date:string;label:string;ms:number;start:string;end:string;tutor:string;link:string;schoolId?:string;schoolName?:string;programId?:string;programName?:string;className?:string;status:Status;groupId?:string};
const norm=(v:unknown)=>String(v||'').trim().toLowerCase();
const mins=(v:string)=>{const m=String(v||'').match(/(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/i);if(!m)return 0;let h=+m[1],n=+(m[2]||0);if(m[3]?.toLowerCase()==='pm'&&h<12)h+=12;if(m[3]?.toLowerCase()==='am'&&h===12)h=0;return h*60+n};
const today=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const label=(v:string)=>{const d=new Date(`${v}T12:00:00`);if(Number.isNaN(d.getTime()))return v;const n=d.getDate(),s=n%10===1&&n%100!==11?'st':n%10===2&&n%100!==12?'nd':n%10===3&&n%100!==13?'rd':'th';return`${d.toLocaleDateString('en-NG',{weekday:'long'})}, ${n}${s} ${d.toLocaleDateString('en-NG',{month:'long'})} ${d.getFullYear()}`};
const status=(date:string,start:string,end:string,explicit?:string):Status=>{const s=norm(explicit).toUpperCase();if(s==='ABSENT')return'absent';if(s==='CANCELLED')return'cancelled';if(s==='RESCHEDULED')return'rescheduled';if(s==='COMPLETED'||s==='ATTENDED')return'completed';const t=today();if(date>t)return'upcoming';if(date<t)return'completed';const n=new Date().getHours()*60+new Date().getMinutes();return n<mins(start)?'upcoming':n<=mins(end)?'ongoing':'completed'};
const same=(a:unknown,b:unknown)=>{const x=norm(a),y=norm(b);return!!(x&&y&&(x===y||x.includes(y)||y.includes(x)))};

const PortalCalendar:React.FC=()=>{
 const role=norm(sessionStorage.getItem('userRole')).toUpperCase(), student=role==='STUDENT', manage=['STAFF','TUTOR','INSTRUCTOR','FACULTY'].includes(role);
 const [ctx,setCtx]=useState({id:sessionStorage.getItem('studentDocId')||'',email:sessionStorage.getItem('studentEmail')||'',schoolId:sessionStorage.getItem('studentSchoolId')||sessionStorage.getItem('schoolId')||'',schoolName:sessionStorage.getItem('studentSchoolName')||'',className:sessionStorage.getItem('studentClass')||'',programId:sessionStorage.getItem('studentProgramId')||sessionStorage.getItem('studentProgrammeId')||'',programName:sessionStorage.getItem('studentProgramName')||sessionStorage.getItem('studentProgrammeName')||sessionStorage.getItem('studentPlan')||sessionStorage.getItem('studentTrack')||''});
 const [events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[program,setProgram]=useState('ALL'),[filterStatus,setFilterStatus]=useState<'ALL'|Status>('ALL'),[expanded,setExpanded]=useState<Record<string,boolean>>({}),[editing,setEditing]=useState<Event|null>(null),[form,setForm]=useState({title:'',date:'',start:'',end:'',link:''}),[saving,setSaving]=useState(false),[updating,setUpdating]=useState<string|null>(null),[,tick]=useState(0);
 useEffect(()=>{if(!student)return;void(async()=>{try{const id=sessionStorage.getItem('studentDocId')||'';if(!id)return;const s=await getDoc(doc(db,'students',id));if(!s.exists())return;const d=s.data() as any;const next={id,email:d.email||ctx.email,schoolId:d.schoolId||ctx.schoolId,schoolName:d.schoolName||d.school||ctx.schoolName,className:d.class||d.grade||d.classLevel||d.year||ctx.className,programId:d.programId||d.assignedProgramId||d.programmeId||ctx.programId,programName:d.programName||d.program||d.programmeName||d.plan||d.track||ctx.programName};setCtx(next);sessionStorage.setItem('studentSchoolId',next.schoolId);sessionStorage.setItem('studentSchoolName',next.schoolName);sessionStorage.setItem('studentClass',next.className);if(next.programId)sessionStorage.setItem('studentProgramId',next.programId);if(next.programName)sessionStorage.setItem('studentProgramName',next.programName)}catch(e){console.warn('Student schedule identity refresh failed:',e)}})()},[student]);
 const load=useCallback(async()=>{setLoading(true);setMessage('');try{const u=auth.currentUser;if(!u)throw new Error('Please sign in again.');const token=await u.getIdToken();const schoolId=student?ctx.schoolId:sessionStorage.getItem('schoolId')||'',studentId=student?ctx.id:'';const r=await fetch(`/.netlify/functions/class-schedules?schoolId=${encodeURIComponent(schoolId)}&studentId=${encodeURIComponent(studentId)}`,{headers:{Authorization:`Bearer ${token}`}});const p=r.ok?await r.json():{schedules:[]};const seen=new Set<string>();const rows=(Array.isArray(p.schedules)?p.schedules:[] as Raw[]).filter((x:Raw)=>{if(!x?.id||seen.has(x.id))return false;seen.add(x.id);if(!student)return true;const direct=(!!x.studentId&&x.studentId===ctx.id)||(!!x.studentEmail&&norm(x.studentEmail)===norm(ctx.email));if(direct)return true;const schoolOk=(!!ctx.schoolId&&x.schoolId===ctx.schoolId)||same(x.schoolName,ctx.schoolName);if(!schoolOk)return false;const pid=x.programId||x.programmeId||'',pn=x.programName||x.programmeName||x.title||'';if(pid||x.programName||x.programmeName){const programOk=(!!ctx.programId&&!!pid&&ctx.programId===pid)||same(pn,ctx.programName);if(!programOk)return false}return isStudentClassMatch(ctx.className,x.classLevel,x.classLevels)});const mapped=rows.map((x:Raw)=>{const date=String(x.date||'').slice(0,10),start=String(x.startTime||'08:00'),end=String(x.endTime||'08:40');if(!date)return null;return{id:x.id,title:x.title||x.programName||x.programmeName||'Class Session',date,label:label(date),ms:new Date(`${date}T12:00:00`).getTime(),start,end,tutor:x.tutorName||'Tutor not assigned',link:x.meetingLink||x.url||'',schoolId:x.schoolId,schoolName:x.schoolName,programId:x.programId||x.programmeId,programName:x.programName||x.programmeName||x.title,className:x.classLevel||(x.classLevels||[]).join(', ')||'All classes',status:status(date,start,end,x.status),groupId:x.scheduleGroupId} as Event}).filter(Boolean) as Event[];mapped.sort((a,b)=>a.ms-b.ms||mins(a.start)-mins(b.start));setEvents(mapped);if(!mapped.length)setMessage(student?'No class schedules are currently assigned to your class and programme.':'No class schedules are currently available.')}catch(e:any){console.error(e);setEvents([]);setMessage(e?.message||'Schedule data could not be loaded.')}finally{setLoading(false)}},[student,ctx]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{const i=window.setInterval(()=>tick(v=>v+1),30000);return()=>window.clearInterval(i)},[]);
 const programs=useMemo(()=>Array.from(new Map(events.filter(e=>e.programName).map(e=>[norm(e.programName),e.programName!])).values()),[events]);
 const filtered=useMemo(()=>events.filter(e=>(program==='ALL'||e.programName===program)&&(filterStatus==='ALL'||e.status===filterStatus)),[events,program,filterStatus]);
 const groups=useMemo(()=>{const m=new Map<string,Event[]>();filtered.forEach(e=>{if(!m.has(e.date))m.set(e.date,[]);m.get(e.date)!.push(e)});return Array.from(m.entries())},[filtered]);
 const current=filtered.find(e=>e.status==='ongoing'),next=filtered.find(e=>e.status==='upcoming');
 const badge=(s:Status)=>{const m:any={ongoing:{t:'Ongoing now',c:'bg-emerald-500 text-white',icon:<span className="h-2 w-2 rounded-full bg-white animate-pulse"/>},upcoming:{t:'Upcoming',c:'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200',icon:<Timer size={12}/>},scheduled:{t:'Scheduled',c:'bg-slate-100 text-slate-700',icon:<CalendarIcon size={12}/>},completed:{t:'Completed',c:'bg-sky-50 text-sky-700 dark:bg-sky-950/40 dark:text-sky-300',icon:<CheckCircle2 size={12}/>},absent:{t:'Absent',c:'bg-rose-50 text-rose-700',icon:<CircleAlert size={12}/>},cancelled:{t:'Cancelled',c:'bg-rose-50 text-rose-700',icon:<CircleAlert size={12}/>},rescheduled:{t:'Rescheduled',c:'bg-amber-50 text-amber-700',icon:<CalendarIcon size={12}/>}}[s];return<span className={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-[10px] font-black uppercase ${m.c}`}>{m.icon}{m.t}</span>};
 const updateStatus=async(e:Event,s:'COMPLETED'|'ABSENT'|'CANCELLED'|'RESCHEDULED')=>{if(!manage)return;setUpdating(e.id);try{const u=auth.currentUser;if(!u)throw new Error('Please sign in again.');const r=await fetch('/.netlify/functions/class-schedules',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await u.getIdToken()}`},body:JSON.stringify({scheduleId:e.id,status:s})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to update class status.');await load()}catch(e:any){setMessage(e?.message||'Unable to update class status.')}finally{setUpdating(null)}};
 const openEdit=(e:Event)=>{setEditing(e);setForm({title:e.title,date:e.date,start:e.start,end:e.end,link:e.link})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!editing||!manage)return;if(mins(form.end)<=mins(form.start)){setMessage('End time must be later than start time.');return}setSaving(true);try{const u=auth.currentUser;if(!u)throw new Error('Please sign in again.');const r=await fetch('/.netlify/functions/class-schedules',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await u.getIdToken()}`},body:JSON.stringify({scheduleId:editing.id,title:form.title,date:form.date,startTime:form.start,endTime:form.end,meetingLink:form.link})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to save schedule.');setEditing(null);await load()}catch(e:any){setMessage(e?.message||'Unable to save schedule.')}finally{setSaving(false)}};
 return <div className="space-y-5"><SEO title="Class Schedules | Jaystarbliss Studios" description="Programme-based class schedules and current class status." noindex={true}/><section className="rounded-3xl overflow-hidden border border-slate-200/80 dark:border-slate-800 bg-white dark:bg-slate-900"><div className="p-5 md:p-7 bg-slate-950 text-white"><div className="flex flex-col xl:flex-row xl:items-end xl:justify-between gap-5"><div><div className="flex items-center gap-2 text-brand-red text-[10px] font-black uppercase tracking-[0.18em] mb-2"><CalendarIcon size={14}/> Class Schedules</div><h1 className="text-2xl md:text-3xl font-black">{student?'Your class schedule':'Class schedules'}</h1><p className="mt-2 text-xs md:text-sm text-slate-300 max-w-2xl">{student?`Showing only ${ctx.className||'your class'} schedules${ctx.programName?` for ${ctx.programName}`:''}.`:'Schedules are listed chronologically and grouped by date.'}</p></div><div className="flex flex-wrap gap-2">{!student&&programs.length>0&&<select value={program} onChange={e=>setProgram(e.target.value)} className="rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs font-bold text-white"><option value="ALL" className="text-slate-900">All programmes</option>{programs.map(p=><option key={p} value={p} className="text-slate-900">{p}</option>)}</select>}<select value={filterStatus} onChange={e=>setFilterStatus(e.target.value as any)} className="rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs font-bold text-white"><option value="ALL" className="text-slate-900">All statuses</option><option value="upcoming" className="text-slate-900">Upcoming</option><option value="ongoing" className="text-slate-900">Ongoing</option><option value="completed" className="text-slate-900">Completed</option><option value="absent" className="text-slate-900">Absent</option></select></div></div></div>{(current||next)&&<div className="p-4 md:p-5 bg-slate-50 dark:bg-slate-950/50 border-t border-slate-200 dark:border-slate-800"><div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><div className="flex items-center gap-2 mb-2">{badge((current||next)!.status)}<span className="text-[11px] text-slate-500">{(current||next)!.label}</span></div><h2 className="text-lg font-black text-slate-900 dark:text-white">{(current||next)!.title}</h2><p className="mt-1 text-xs text-slate-500"><Clock size={13} className="inline mr-1"/>{(current||next)!.start} – {(current||next)!.end} · {(current||next)!.tutor}</p></div>{(current||next)!.link&&<a href={(current||next)!.link} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-brand-red px-4 py-2.5 text-xs font-black text-white"><Video size={14}/> Join class <ExternalLink size={12}/></a>}</div></div>}</section>
 {loading?<div className="min-h-56 rounded-3xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 flex items-center justify-center gap-3 text-sm font-bold text-slate-500"><Loader2 size={18} className="animate-spin"/> Loading schedules…</div>:message&&!groups.length?<div className="min-h-56 rounded-3xl border border-dashed border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 flex flex-col items-center justify-center text-center px-6"><CalendarIcon size={30} className="text-slate-400 mb-3"/><h2 className="text-base font-black text-slate-800 dark:text-white">No schedules found</h2><p className="mt-1 max-w-md text-xs text-slate-500">{message}</p></div>:<div className="space-y-4">{groups.map(([date,rows])=>{const open=expanded[date]!==false;return<section key={date} className="rounded-3xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden"><button type="button" onClick={()=>setExpanded(v=>({...v,[date]:!open}))} className="w-full px-5 py-4 flex justify-between text-left"><div><p className="text-sm font-black text-slate-900 dark:text-white">{rows[0].label}</p><p className="text-[11px] text-slate-500">{rows.length} session{rows.length===1?'':'s'}</p></div><span className="text-xs font-black text-slate-500">{open?'Hide':'Show'}</span></button>{open&&<div className="border-t border-slate-100 dark:border-slate-800 divide-y divide-slate-100 dark:divide-slate-800">{rows.map(e=><article key={e.id} className="p-5 flex flex-col lg:flex-row lg:items-center gap-4"><div className="w-28 shrink-0"><p className="text-sm font-black text-slate-900 dark:text-white">{e.start}</p><p className="text-[11px] text-slate-400">to {e.end}</p></div><div className="flex-1 min-w-0"><div className="flex flex-wrap gap-2 items-center">{badge(e.status)}{e.className&&<span className="text-[10px] font-bold px-2 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300">{e.className}</span>}</div><h3 className="mt-2 text-sm font-black text-slate-900 dark:text-white">{e.title}</h3><p className="mt-1 text-xs text-slate-500">{e.programName||'Programme session'} · {e.tutor}</p></div><div className="flex gap-2 shrink-0">{e.link&&<a href={e.link} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 dark:border-slate-700 px-3 py-2 text-[11px] font-black"><Video size={13}/> Join</a>}{manage&&<><button type="button" onClick={()=>openEdit(e)} className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 dark:border-slate-700 px-3 py-2 text-[11px] font-black"><Edit3 size={13}/> Edit</button><button type="button" disabled={updating===e.id} onClick={()=>void updateStatus(e,'COMPLETED')} className="rounded-xl bg-slate-900 text-white px-3 py-2 text-[11px] font-black disabled:opacity-50">{updating===e.id?'Saving…':'Complete'}</button></>}</div></article>)}</div>}</section>})}</div>}
 {editing&&manage&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60"><form onSubmit={save} className="w-full max-w-lg rounded-3xl bg-white dark:bg-slate-900 p-6 space-y-4"><div className="flex justify-between"><div><h2 className="text-lg font-black">Edit class session</h2><p className="text-xs text-slate-500">Edit this occurrence without changing other sessions.</p></div><button type="button" onClick={()=>setEditing(null)}><X size={18}/></button></div><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="w-full rounded-xl border px-3 py-2.5 text-sm" placeholder="Class title"/><div className="grid grid-cols-3 gap-3"><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"/><input type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"/><input type="time" value={form.end} onChange={e=>setForm({...form,end:e.target.value})} className="rounded-xl border px-3 py-2.5 text-sm"/></div><input value={form.link} onChange={e=>setForm({...form,link:e.target.value})} className="w-full rounded-xl border px-3 py-2.5 text-sm" placeholder="Meeting link"/><button disabled={saving} className="w-full rounded-xl bg-brand-red text-white py-3 text-xs font-black inline-flex justify-center gap-2">{saving?<Loader2 size={14} className="animate-spin"/>:<Save size={14}/>} Save changes</button></form></div>}
 </div>};
export default PortalCalendar;
