import React, { useEffect, useState } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import { Download, FileText, Image as ImageIcon, Loader2, UserPlus, Printer, ShieldCheck, BookOpen } from 'lucide-react';
import SEO from '../../components/ui/SEO';
import { auth, db } from '../../lib/firebase';
import { useToast } from '../../contexts/ToastContext';

const SchoolStudentOnboardingV2: React.FC = () => {
  const { toast } = useToast();
  const [programs, setPrograms] = useState<any[]>([]); const [form, setForm] = useState({ fullName:'', username:'', email:'', class:'JSS 1', programId:'', parentId:'' }); const [saving,setSaving]=useState(false); const [credentials,setCredentials]=useState<any>(null);
  useEffect(()=>{ getDocs(collection(db,'programs')).then(s=>setPrograms(s.docs.map(d=>({id:d.id,...d.data()})))).catch(()=>undefined); },[]);
  const update=(key:string,value:string)=>setForm(p=>({...p,[key]:value}));
  const onboard=async(e:React.FormEvent)=>{e.preventDefault();if(!auth.currentUser)return toast.error('Your school session has expired.');if(!form.fullName||!form.username||!form.class)return toast.error('Complete the required student fields.');setSaving(true);try{const token=await auth.currentUser.getIdToken();const program=programs.find(p=>p.id===form.programId);const response=await fetch('/.netlify/functions/school-student-onboard',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({...form,programName:program?.name||''})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to onboard student.');setCredentials(result.credentials);setForm({fullName:'',username:'',email:'',class:'JSS 1',programId:'',parentId:''});toast.success(`Student account created${result.student?.programName?` and enrolled in ${result.student.programName}`:''}.`);}catch(error){toast.error(error instanceof Error?error.message:'Unable to onboard student.');}finally{setSaving(false);}};
  const text=credentials?`JAYSTARBLISS STUDIOS — STUDENT ACCESS\n\nUsername: ${credentials.username}\nAccess Code: ${credentials.accessCode}\nStudent Portal: ${window.location.origin}${credentials.portal}\n\nKeep these credentials private.`:'';
  const downloadText=()=>{if(!text)return;const blob=new Blob([text],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${credentials.username}-student-access.txt`;a.click();URL.revokeObjectURL(url);};
  const print=()=>{if(!credentials)return;const w=window.open('','_blank','noopener,noreferrer');if(!w)return toast.error('Allow pop-ups to print.');w.document.write(`<html><head><title>Student Access</title><style>body{font-family:Arial;padding:48px}.card{max-width:560px;border:2px solid #b91c1c;border-radius:20px;padding:32px}.label{font-size:12px;color:#64748b;text-transform:uppercase;letter-spacing:.08em}.value{font-size:22px;font-weight:800;margin:6px 0 20px}</style></head><body><div class="card"><h1>Jaystarbliss Studios</h1><h2>Student Portal Access</h2><div class="label">Username</div><div class="value">${credentials.username}</div><div class="label">Access Code</div><div class="value">${credentials.accessCode}</div><div class="label">Portal</div><div class="value">${window.location.origin}${credentials.portal}</div></div><script>window.onload=()=>window.print()</script></body></html>`);w.document.close();};
  return <div className="space-y-6"><SEO title="Onboard School Student | Jaystarbliss Studios" description="Create secure student access and connect the learner to a programme." noindex/><div className="pro-surface rounded-3xl p-6 md:p-8"><div className="flex items-start gap-3"><div className="rounded-2xl bg-brand-red/10 p-3 text-brand-red"><UserPlus size={22}/></div><div><div className="text-xs uppercase tracking-widest font-black text-brand-red">School Operations</div><h1 className="text-2xl md:text-3xl font-black mt-1">Onboard a student</h1><p className="text-sm text-slate-500 mt-2 max-w-2xl">Create the learner once, connect them to a programme, and issue secure portal credentials.</p></div></div></div>
  <form onSubmit={onboard} className="pro-surface rounded-2xl p-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Student full name" value={form.fullName} onChange={v=>update('fullName',v)} required/><Field label="Username" value={form.username} onChange={v=>update('username',v)} required/><Field label="Email (optional)" value={form.email} onChange={v=>update('email',v)} type="email"/><label className="text-sm font-bold">Class<select value={form.class} onChange={e=>update('class',e.target.value)} className="mt-2 w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-white"><option>Primary 4</option><option>Primary 5</option><option>JSS 1</option><option>JSS 2</option><option>JSS 3</option><option>SS 1</option><option>SS 2</option><option>SS 3</option></select></label><label className="text-sm font-bold md:col-span-2"><span className="flex items-center gap-2">Programme <BookOpen size={14} className="text-brand-red"/></span><select value={form.programId} onChange={e=>update('programId',e.target.value)} className="mt-2 w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-white"><option value="">Select a programme (optional)</option>{programs.map(p=><option key={p.id} value={p.id}>{p.name||p.title}</option>)}</select><span className="mt-1 block text-xs font-normal text-slate-500">When selected, an active enrollment is created for this learner.</span></label><Field label="Parent account ID (optional)" value={form.parentId} onChange={v=>update('parentId',v)}/></div><button disabled={saving} className="min-h-11 mt-5 rounded-xl bg-brand-red text-white px-5 text-sm font-black inline-flex items-center gap-2"><ShieldCheck size={16}/>{saving?<><Loader2 size={16} className="animate-spin"/>Creating secure access…</>:'Create Student & Enrollment'}</button></form>
  {credentials&&<div className="pro-surface rounded-2xl p-6 border-2 border-brand-red/20"><div className="flex items-start gap-3"><div className="rounded-xl bg-brand-red/10 p-3 text-brand-red"><ShieldCheck size={20}/></div><div><h2 className="font-black text-xl">Credentials created</h2><p className="text-sm text-slate-500 mt-1">Save or distribute these credentials now.</p></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-5"><Credential label="Username" value={credentials.username}/><Credential label="Access code" value={credentials.accessCode}/></div><div className="flex flex-wrap gap-3 mt-5"><button type="button" onClick={downloadText} className="min-h-11 rounded-xl border border-slate-200 px-4 text-xs font-black inline-flex items-center gap-2"><FileText size={15}/>TXT</button><button type="button" onClick={print} className="min-h-11 rounded-xl border border-slate-200 px-4 text-xs font-black inline-flex items-center gap-2"><Printer size={15}/>Print / PDF</button><a href="/portal" className="min-h-11 rounded-xl bg-brand-slate text-white px-4 text-xs font-black inline-flex items-center gap-2"><Download size={15}/>Student Portal</a><button type="button" onClick={()=>setCredentials(null)} className="min-h-11 rounded-xl border border-slate-200 px-4 text-xs font-black">Done</button></div></div>}
  </div>;
};
const Field=({label,value,onChange,type='text',required=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean})=><label className="text-sm font-bold">{label}<input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full min-h-11 rounded-xl border border-slate-200 px-3 bg-white"/></label>;
const Credential=({label,value}:{label:string;value:string})=><div className="rounded-2xl bg-slate-50 p-4"><div className="text-[11px] uppercase tracking-widest text-slate-500 font-black">{label}</div><div className="text-xl font-black mt-1 break-all">{value}</div></div>;
export default SchoolStudentOnboardingV2;
