import React,{useCallback,useEffect,useState}from"react";
import{CalendarDays,CheckCircle2,Clock3,Edit3,Loader2,Plus,RefreshCw,School,XCircle}from"lucide-react";
import SEO from"../../components/ui/SEO";import{auth,db}from"../../lib/firebase";import{collection,getDocs}from"firebase/firestore";import{useToast}from"../../contexts/ToastContext";
const CLASS_OPTIONS=["Year 1","Year 2","Year 3","Year 4","Year 5","JSS 1","JSS 2","JSS 3","SS1","SS2","SS3"];const STATUS_OPTIONS=["SCHEDULED","COMPLETED","ATTENDED","ABSENT","CANCELLED","RESCHEDULED"];
type Schedule=Record<string,any>&{id:string};type School={id:string;name:string};type Group=Record<string,any>&{scheduleGroupId:string;classLevels:string[];occurrences:Schedule[]};
const AdminClassSchedules:React.FC=()=>{
const{toast}=useToast();const[schools,setSchools]=useState<School[]>([]);const[groups,setGroups]=useState<Group[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[filterSchool,setFilterSchool]=useState("");const[showForm,setShowForm]=useState(false);const[editing,setEditing]=useState<Group|null>(null);
const[form,setForm]=useState({schoolId:"",scope:"all",rangeStart:"Year 1",rangeEnd:"Year 5",classLevels:["Year 1"],title:"Coding Class",tutorName:"",startDate:new Date().toISOString().slice(0,10),startTime:"09:00",endTime:"11:00",recurring:true,weeks:"52"});
const load=useCallback(async()=>{setLoading(true);try{const schoolSnap=await getDocs(collection(db,"schools"));setSchools(schoolSnap.docs.map(d=>({id:d.id,name:String(d.data().name||d.data().schoolName||d.id)})).sort((a,b)=>a.name.localeCompare(b.name)));const user=auth.currentUser;if(!user)throw new Error("Authentication required.");const token=await user.getIdToken(true);const url="/.netlify/functions/class-schedules"+(filterSchool?"?schoolId="+encodeURIComponent(filterSchool):"");const response=await fetch(url,{headers:{Authorization:"Bearer "+token}});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to load class schedules.");setGroups(Array.isArray(result.groups)?result.groups:[]);}catch(e){toast.error(e instanceof Error?e.message:"Unable to load schedules.");}finally{setLoading(false);}},[filterSchool,toast]);
useEffect(()=>{void load()},[load]);
const resolvedClasses=()=>{if(form.scope==="all")return CLASS_OPTIONS;if(form.scope==="range"){const a=CLASS_OPTIONS.indexOf(form.rangeStart),b=CLASS_OPTIONS.indexOf(form.rangeEnd);return CLASS_OPTIONS.slice(Math.min(a,b),Math.max(a,b)+1)}return form.classLevels};
const openCreate=()=>{setEditing(null);setForm({schoolId:filterSchool||"",scope:"all",rangeStart:"Year 1",rangeEnd:"Year 5",classLevels:["Year 1"],title:"Coding Class",tutorName:"",startDate:new Date().toISOString().slice(0,10),startTime:"09:00",endTime:"11:00",recurring:true,weeks:"52"});setShowForm(true)};
const openEdit=(g:Group)=>{const levels=g.classLevels?.length?g.classLevels:Array.from(new Set((g.occurrences||[]).map((x:any)=>x.classLevel).filter(Boolean)));const contiguous=levels.length>1&&CLASS_OPTIONS.slice(CLASS_OPTIONS.indexOf(levels[0]),CLASS_OPTIONS.indexOf(levels[levels.length-1])+1).every(x=>levels.includes(x));setEditing(g);setForm({schoolId:g.schoolId||"",scope:levels.length===CLASS_OPTIONS.length?"all":contiguous?"range":"specific",rangeStart:levels[0]||"Year 1",rangeEnd:levels[levels.length-1]||"Year 5",classLevels:levels.length?levels:["Year 1"],title:g.title||"",tutorName:g.tutorName||"",startDate:g.startDate||g.occurrences?.[0]?.date||new Date().toISOString().slice(0,10),startTime:g.startTime||"09:00",endTime:g.endTime||"11:00",recurring:g.recurring!==false,weeks:String(g.weeks||g.occurrences?.[0]?.occurrenceTotal||52)});setShowForm(true)};
const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!form.schoolId)return toast.error("Select a school.");const levels=resolvedClasses();if(!levels.length)return toast.error("Select at least one class.");if(form.endTime<=form.startTime)return toast.error("End time must be later than start time.");setSaving(true);try{const user=auth.currentUser;if(!user)throw new Error("Authentication required.");const token=await user.getIdToken(true);const school=schools.find(s=>s.id===form.schoolId);const body={...form,classLevels:levels,classLevel:levels[0],schoolName:school?.name||"",weeks:Number(form.weeks)||52,...(editing?{scheduleGroupId:editing.scheduleGroupId}: {})};const response=await fetch("/.netlify/functions/class-schedules",{method:editing?"PATCH":"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||(editing?"Unable to update schedule.":"Unable to create schedule."));toast.success(editing?"Recurring schedule updated.":"Schedule created for "+levels.length+" class"+(levels.length===1?"":"es")+".");setShowForm(false);setEditing(null);await load();}catch(e){toast.error(e instanceof Error?e.message:"Unable to save schedule.");}finally{setSaving(false)}};
const setStatus=async(id:string,status:string)=>{try{const user=auth.currentUser;if(!user)throw new Error("Authentication required.");const token=await user.getIdToken(true);const response=await fetch("/.netlify/functions/class-schedules",{method:"PATCH",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({scheduleId:id,status})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to update class.");setGroups(prev=>prev.map(g=>({...g,occurrences:g.occurrences.map((s:any)=>s.id===id?{...s,status}:s)})));}catch(e){toast.error(e instanceof Error?e.message:"Unable to update class.");}};
const openFormTitle=editing?"Edit recurring schedule":"Create recurring schedule";
return <div className="space-y-6"><SEO title="Class Schedules | Admin" description="Manage school-wide recurring class schedules." noindex/>
<div className="pro-surface rounded-3xl p-6 md:p-8 flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h1 className="text-2xl md:text-3xl font-black text-slate-900 dark:text-white">Class Schedules</h1><p className="text-sm text-slate-500 dark:text-slate-400 mt-1 max-w-3xl">Create recurring schedules for an entire school, every class, or a class range. Edit the recurring setup later without rebuilding it manually.</p></div><div className="flex gap-2"><button type="button" onClick={()=>void load()} className="min-h-11 rounded-xl border border-slate-200 dark:border-slate-700 px-4 text-xs font-black inline-flex items-center gap-2"><RefreshCw size={15}/>Refresh</button><button type="button" onClick={openCreate} className="min-h-11 rounded-xl bg-brand-red text-white px-4 text-xs font-black inline-flex items-center gap-2"><Plus size={15}/>New Schedule</button></div></div>
<div className="pro-surface rounded-2xl p-4"><label className="text-[11px] uppercase tracking-wider font-black text-slate-500">School</label><select value={filterSchool} onChange={e=>setFilterSchool(e.target.value)} className={inputClass+" mt-1"}><option value="">All schools</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>
{showForm&&<form onSubmit={submit} className="pro-surface rounded-2xl p-5 md:p-6 space-y-5"><div className="flex items-center justify-between"><div><h2 className="font-black text-lg text-slate-900 dark:text-white">{openFormTitle}</h2><p className="text-xs text-slate-500 mt-1">{editing?"Changes are applied to this recurring schedule group.":"One setup can cover the whole school or a selected class range."}</p></div><button type="button" onClick={()=>{setShowForm(false);setEditing(null)}} className="p-2 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800"><XCircle size={18}/></button></div>
<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"><Field label="School"><select value={form.schoolId} onChange={e=>setForm({...form,schoolId:e.target.value})} className={inputClass}><option value="">Select school</option>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Coverage"><select value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})} className={inputClass}><option value="all">All classes in school</option><option value="range">Class range</option><option value="specific">Selected classes</option></select></Field>
{form.scope==="range"&&<><Field label="From"><select value={form.rangeStart} onChange={e=>setForm({...form,rangeStart:e.target.value})} className={inputClass}>{CLASS_OPTIONS.map(c=><option key={c}>{c}</option>)}</select></Field><Field label="To"><select value={form.rangeEnd} onChange={e=>setForm({...form,rangeEnd:e.target.value})} className={inputClass}>{CLASS_OPTIONS.map(c=><option key={c}>{c}</option>)}</select></Field></>}
{form.scope==="specific"&&<Field label="Classes"><div className="grid grid-cols-2 gap-2 max-h-32 overflow-y-auto rounded-xl border border-slate-200 dark:border-slate-700 p-2">{CLASS_OPTIONS.map(c=><label key={c} className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={form.classLevels.includes(c)} onChange={e=>setForm(f=>({...f,classLevels:e.target.checked?Array.from(new Set([...f.classLevels,c])):f.classLevels.filter(x=>x!==c)}))}/>{c}</label>)}</div></Field>}
<Field label="Class / programme title"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className={inputClass} placeholder="e.g. Coding & Tech"/></Field><Field label="Tutor / instructor"><input value={form.tutorName} onChange={e=>setForm({...form,tutorName:e.target.value})} className={inputClass} placeholder="Assigned tutor"/></Field><Field label="First class date"><input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} className={inputClass}/></Field><Field label="Start time"><input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})} className={inputClass}/></Field><Field label="End time"><input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})} className={inputClass}/></Field><Field label="Recurrence"><select value={form.recurring?"yes":"no"} onChange={e=>setForm({...form,recurring:e.target.value==="yes"})} className={inputClass}><option value="yes">Every week</option><option value="no">One-time class</option></select></Field>{form.recurring&&<Field label="Number of weeks"><input type="number" min="1" max="52" value={form.weeks} onChange={e=>setForm({...form,weeks:e.target.value})} className={inputClass}/></Field>}</div>
<div className="rounded-2xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800 p-4 text-xs text-slate-600 dark:text-slate-300"><strong>Coverage:</strong> {resolvedClasses().join(", ")||"No classes selected"}. <span className="block mt-1">Duration: {form.startTime}–{form.endTime}. {form.recurring?"Repeats weekly for "+form.weeks+" weeks.":"One-time class."}</span></div><button disabled={saving} className="min-h-11 rounded-xl bg-brand-red text-white px-5 text-xs font-black inline-flex items-center gap-2">{saving?<Loader2 size={15} className="animate-spin"/>:editing?<Edit3 size={15}/>:<CalendarDays size={15}/>} {saving?"Saving…":editing?"Save Changes":"Create Schedule"}</button></form>}
<div className="space-y-4">{loading?<div className="pro-surface rounded-2xl p-10 text-center text-sm text-slate-500"><Loader2 className="animate-spin mx-auto mb-2" size={20}/>Loading schedules…</div>:groups.length===0?<div className="pro-surface rounded-2xl p-10 text-center"><CalendarDays className="mx-auto text-slate-400" size={30}/><p className="font-black mt-3 text-slate-900 dark:text-white">No recurring schedules yet</p></div>:groups.map(g=><div key={g.scheduleGroupId} className="pro-surface rounded-2xl p-5"><div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-4"><div><div className="flex items-center gap-2"><School size={16} className="text-brand-red"/><span className="text-[11px] uppercase tracking-wider font-black text-brand-red">{schools.find(s=>s.id===g.schoolId)?.name||g.schoolName||"School"}</span></div><h3 className="mt-1 text-lg font-black text-slate-900 dark:text-white">{g.title}</h3><p className="text-xs text-slate-500 mt-1">{g.tutorName||"No tutor assigned"} · {g.startTime}–{g.endTime}</p><p className="text-xs text-slate-600 dark:text-slate-300 mt-2"><strong>Classes:</strong> {g.classLevels?.length===CLASS_OPTIONS.length?"All classes":g.classLevels?.join(", ")}</p></div><button type="button" onClick={()=>openEdit(g)} className="min-h-10 rounded-xl border border-slate-200 dark:border-slate-700 px-4 text-xs font-black inline-flex items-center gap-2"><Edit3 size={14}/>Edit recurring schedule</button></div>
<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-xs min-w-[850px]"><thead><tr>{["Date","Class","Time","Status","Update"].map(h=><th key={h} className="px-3 py-2 font-black uppercase tracking-wider text-slate-500">{h}</th>)}</tr></thead><tbody>{g.occurrences.slice(0,30).map((s:any)=><tr key={s.id} className="border-t border-slate-100 dark:border-slate-800"><td className="px-3 py-2 font-bold">{new Date(s.date+"T00:00:00").toLocaleDateString("en-NG",{dateStyle:"medium"})}</td><td className="px-3 py-2">{s.classLevel}</td><td className="px-3 py-2 whitespace-nowrap"><Clock3 size={12} className="inline mr-1"/>{s.startTime}–{s.endTime}</td><td className="px-3 py-2"><Status status={s.status}/></td><td className="px-3 py-2"><select value={s.status} onChange={e=>void setStatus(s.id,e.target.value)} className={inputClass+" min-h-8 w-auto px-2"}>{STATUS_OPTIONS.map(v=><option key={v}>{v}</option>)}</select></td></tr>)}</tbody></table>{g.occurrences.length>30&&<p className="text-[11px] text-slate-500 mt-2">Showing first 30 occurrences in this recurring group.</p>}</div></div>)}</div></div>};
const inputClass="w-full min-h-11 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-950 text-slate-900 dark:text-white px-3";
const Field:React.FC<{label:string;children:React.ReactNode}>=({label,children})=><label className="text-xs font-black text-slate-700 dark:text-slate-300">{label}<div className="mt-1">{children}</div></label>;
const Status:React.FC<{status:string}>=({status})=><span className={"inline-flex items-center gap-1 px-2 py-1 rounded-full text-[10px] font-black "+(status==="COMPLETED"||status==="ATTENDED"?"bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300":status==="CANCELLED"||status==="ABSENT"?"bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-300":"bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300")}>{status==="COMPLETED"||status==="ATTENDED"?<CheckCircle2 size={11}/>:<Clock3 size={11}/>} {status}</span>;
export default AdminClassSchedules;