import React, { useEffect, useMemo, useState } from 'react';
import { Activity, CheckCircle2, DollarSign, Edit3, Loader2, Save, ShieldCheck, TrendingUp, Users, Wallet } from 'lucide-react';
import { billingGet, billingPost, dateLabel, formatNaira } from '../../lib/billing';
import SEO from '../../components/ui/SEO';
import { useToast } from '../../contexts/ToastContext';

type Plan = Record<string, any> & { id: string };
type Policy = { percentage: string; flat: string; cap: string; waiveFlatBelow?: string; enabled: boolean };
const money=(v:any)=>formatNaira(Number(v||0));
const monthKey=(v:any)=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,7)};

const AdminBilling: React.FC = () => {
 const {toast}=useToast(); const [data,setData]=useState<any>({config:{plans:{},parentFeePolicy:{},schoolFeePolicy:{},withdrawalFeePolicy:{}},payments:[],enrollments:[],withdrawals:[],staff:[]}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(''); const [role,setRole]=useState('admin'); const [selectedPlan,setSelectedPlan]=useState(''); const [planDraft,setPlanDraft]=useState({name:'',baseAmount:'',durationWeeks:'',teachingModes:''}); const [parentPolicy,setParentPolicy]=useState<Policy>({percentage:'',flat:'',cap:'',waiveFlatBelow:'',enabled:true}); const [schoolPolicy,setSchoolPolicy]=useState<Policy>({percentage:'',flat:'',cap:'',waiveFlatBelow:'',enabled:true}); const [withdrawalPolicy,setWithdrawalPolicy]=useState<Policy>({percentage:'',flat:'',cap:'',enabled:false}); const [minimumWithdrawal,setMinimumWithdrawal]=useState('10000');
 const load=async()=>{setLoading(true);try{const r=await billingGet<any>('billing-data');setData(r);setRole(String(sessionStorage.getItem('userRole')||r.role||'admin').toLowerCase());setParentPolicy({...r.config.parentFeePolicy});setSchoolPolicy({...r.config.schoolFeePolicy});setWithdrawalPolicy({...r.config.withdrawalFeePolicy});setMinimumWithdrawal(String(r.config.minimumWithdrawalAmount||10000));}catch(e){toast.error(e instanceof Error?e.message:'Unable to load billing operations.')}finally{setLoading(false)}}; useEffect(()=>{void load()},[]);
 const plans=Object.values((data.config?.plans||{}) as Record<string,Plan>); const paid=useMemo(()=> (data.payments||[]).filter((p:any)=>String(p.status).toUpperCase()==='PAID'),[data.payments]); const withdrawals=useMemo(()=>data.withdrawals||[],[data.withdrawals]); const paidWithdrawals=useMemo(()=>withdrawals.filter((w:any)=>['PAID','SUCCESS','SUCCESSFUL'].includes(String(w.status).toUpperCase())),[withdrawals]);
 const totalGross=useMemo(()=>paid.reduce((s:number,p:any)=>s+Number(p.customerTotal||Number(p.amount||0)/100),0),[paid]); const totalFees=useMemo(()=>paid.reduce((s:number,p:any)=>s+Number(p.transactionFee||0),0),[paid]); const tutorAllocated=useMemo(()=>paid.reduce((s:number,p:any)=>s+(p.tutorId?Number(p.baseAmount||Number(p.amount||0)/100):0),0),[paid]); const withdrawalFees=useMemo(()=>paidWithdrawals.reduce((s:number,w:any)=>s+Number(w.serviceFee||0),0),[paidWithdrawals]);
 const monthly=useMemo(()=>{const map:Record<string,any>={};paid.forEach((p:any)=>{const k=monthKey(p.paidAt||p.updatedAt||p.createdAt);if(!k)return;map[k]??={gross:0,gatewayFees:0,tutorAllocated:0,withdrawals:0,withdrawalFees:0,transactions:0};map[k].gross+=Number(p.customerTotal||Number(p.amount||0)/100);map[k].gatewayFees+=Number(p.transactionFee||0);map[k].tutorAllocated+=p.tutorId?Number(p.baseAmount||0):0;map[k].transactions++});paidWithdrawals.forEach((w:any)=>{const k=monthKey(w.paidAt||w.updatedAt||w.createdAt);if(!k)return;map[k]??={gross:0,gatewayFees:0,tutorAllocated:0,withdrawals:0,withdrawalFees:0,transactions:0};map[k].withdrawals+=Number(w.netAmount||0);map[k].withdrawalFees+=Number(w.serviceFee||0)});return Object.entries(map).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,12).map(([month,v])=>({month,...v,platformRevenue:v.gatewayFees+v.withdrawalFees}));},[paid,paidWithdrawals]);
 const editPlan=(p:Plan)=>{setSelectedPlan(p.id);setPlanDraft({name:p.name||'',baseAmount:String(p.baseAmount??''),durationWeeks:String(p.durationWeeks??''),teachingModes:Array.isArray(p.teachingModes)?p.teachingModes.join(', '):''})};
 const savePlan=async()=>{if(!selectedPlan)return;setSaving('plan');try{await billingPost('billing-admin',{action:'update_plan',planId:selectedPlan,name:planDraft.name,baseAmount:Number(planDraft.baseAmount),durationWeeks:Number(planDraft.durationWeeks),teachingModes:planDraft.teachingModes.split(',').map(s=>s.trim()).filter(Boolean)});toast.success('Payment plan updated.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Unable to save plan.')}finally{setSaving('')}};
 const saveFee=async(policyRole:'parent'|'school',policy:Policy)=>{setSaving(policyRole);try{await billingPost('billing-admin',{action:'update_fee_policy',role:policyRole,percentage:Number(policy.percentage),flat:Number(policy.flat),cap:Number(policy.cap),waiveFlatBelow:Number(policy.waiveFlatBelow),enabled:policy.enabled});toast.success('Transaction fee policy updated.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Unable to save fee policy.')}finally{setSaving('')}};
 const saveWithdrawalFee=async()=>{setSaving('withdrawal-fee');try{await billingPost('billing-admin',{action:'set_withdrawal_fee_policy',percentage:Number(withdrawalPolicy.percentage),flat:Number(withdrawalPolicy.flat),cap:Number(withdrawalPolicy.cap),enabled:withdrawalPolicy.enabled});toast.success('Withdrawal service fee updated.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Unable to save withdrawal fee.')}finally{setSaving('')}};
 const saveMinimum=async()=>{setSaving('minimum');try{await billingPost('billing-admin',{action:'set_minimum_withdrawal',amount:Number(minimumWithdrawal)});toast.success('Minimum withdrawal updated.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Unable to save withdrawal rule.')}finally{setSaving('')}};
 const assignTutor=async(payment:any,tutorId:string)=>{if(!tutorId)return;setSaving(payment.id);try{await billingPost('billing-admin',{action:'assign_tutor',paymentId:payment.id,studentId:payment.studentId||'',tutorId});toast.success('Tutor assigned and wallet allocation recorded.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Unable to assign tutor.')}finally{setSaving('')}};
 if(loading)return <div className="py-12 flex justify-center text-sm text-slate-500"><Loader2 className="animate-spin mr-2" size={18}/>Loading billing operations...</div>;
 return <div className="space-y-6"><SEO title="Billing & Wallet Operations | Admin" description="Manage payment plans, fees, transactions and staff wallet allocations." noindex={true}/>
  <div className="pro-surface rounded-3xl p-6 md:p-8"><div className="flex items-center justify-between gap-4"><div><div className="text-brand-red font-black text-xs uppercase tracking-widest flex items-center gap-2"><ShieldCheck size={14}/>Financial Operations</div><h1 className="text-2xl md:text-3xl font-black mt-2">Billing, Paystack & Staff Wallets</h1><p className="text-sm text-slate-500 mt-1">Verified collections, customer fees, tutor allocations and staff payouts in one operational view.</p></div><button type="button" onClick={()=>void load()} className="min-h-11 rounded-xl border border-slate-200 px-4 text-xs font-bold">Refresh</button></div></div>
  <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4"><Metric icon={<DollarSign size={18}/>} label="Gross verified" value={money(totalGross)}/><Metric icon={<Activity size={18}/>} label="Gateway fees" value={money(totalFees)}/><Metric icon={<Users size={18}/>} label="Tutor allocations" value={money(tutorAllocated)}/><Metric icon={<Wallet size={18}/>} label="Withdrawal fees" value={money(withdrawalFees)}/><Metric icon={<TrendingUp size={18}/>} label="Platform fee revenue" value={money(totalFees+withdrawalFees)}/></div>
  {role==='superadmin'&&<><div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><PolicyCard title="Parent transaction fee" policy={parentPolicy} setPolicy={setParentPolicy} saving={saving==='parent'} onSave={()=>void saveFee('parent',parentPolicy)}/><PolicyCard title="School transaction fee" policy={schoolPolicy} setPolicy={setSchoolPolicy} saving={saving==='school'} onSave={()=>void saveFee('school',schoolPolicy)}/></div><div className="pro-surface rounded-2xl p-6"><h2 className="font-black">Staff withdrawal service fee</h2><p className="text-xs text-slate-500 mt-1">Deducted from the staff member's gross withdrawal; only the net amount is transferred.</p><div className="grid grid-cols-1 sm:grid-cols-4 gap-3 mt-4"><input type="number" step="0.01" value={withdrawalPolicy.percentage} onChange={e=>setWithdrawalPolicy({...withdrawalPolicy,percentage:e.target.value})} placeholder="Percent" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input type="number" value={withdrawalPolicy.flat} onChange={e=>setWithdrawalPolicy({...withdrawalPolicy,flat:e.target.value})} placeholder="Flat fee" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input type="number" value={withdrawalPolicy.cap} onChange={e=>setWithdrawalPolicy({...withdrawalPolicy,cap:e.target.value})} placeholder="Fee cap" className="min-h-11 rounded-xl border border-slate-200 px-3"/><label className="min-h-11 rounded-xl border border-slate-200 px-3 flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={withdrawalPolicy.enabled} onChange={e=>setWithdrawalPolicy({...withdrawalPolicy,enabled:e.target.checked})}/>Enable fee</label></div><button disabled={saving==='withdrawal-fee'} onClick={()=>void saveWithdrawalFee()} className="min-h-11 mt-4 rounded-xl bg-brand-slate text-white px-4 text-xs font-bold inline-flex items-center gap-2"><Save size={14}/>{saving==='withdrawal-fee'?'Saving…':'Save withdrawal fee'}</button></div><div className="pro-surface rounded-2xl p-6"><h2 className="font-black">Wallet withdrawal rule</h2><div className="flex flex-wrap gap-3 mt-4"><input type="number" value={minimumWithdrawal} onChange={e=>setMinimumWithdrawal(e.target.value)} className="min-h-11 rounded-xl border border-slate-200 px-3"/><button disabled={saving==='minimum'} onClick={()=>void saveMinimum()} className="min-h-11 rounded-xl bg-brand-slate text-white px-4 text-xs font-bold">Save minimum</button><span className="text-xs text-slate-500 self-center">Current minimum: {money(data.config?.minimumWithdrawalAmount)}</span></div></div></>}
  <div className="pro-surface rounded-2xl p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="font-black">Payment plans</h2><p className="text-xs text-slate-500 mt-1">Pricing changes affect new checkouts.</p></div><Edit3 size={18}/></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{plans.map(plan=><div key={plan.id} className="rounded-2xl border border-slate-200 dark:border-slate-800 p-4"><div className="font-black">{plan.name}</div><div className="text-xs text-slate-500 mt-1">{plan.role} • {plan.durationWeeks} weeks</div><div className="text-2xl font-black mt-2">{money(plan.baseAmount)}</div><div className="text-xs text-slate-500 mt-2">{(plan.teachingModes||[]).join(' • ')}</div>{role==='superadmin'&&<button type="button" onClick={()=>editPlan(plan)} className="min-h-10 mt-4 rounded-lg border border-slate-200 px-3 text-xs font-bold">Edit plan</button>}</div>)}</div></div>
  {selectedPlan&&role==='superadmin'&&<div className="pro-surface rounded-2xl p-6"><div className="flex items-center justify-between"><h2 className="font-black">Edit plan</h2><button type="button" onClick={()=>setSelectedPlan('')} className="text-xs font-bold">Close</button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4"><input value={planDraft.name} onChange={e=>setPlanDraft({...planDraft,name:e.target.value})} placeholder="Plan name" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input type="number" value={planDraft.baseAmount} onChange={e=>setPlanDraft({...planDraft,baseAmount:e.target.value})} placeholder="Base amount" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input type="number" value={planDraft.durationWeeks} onChange={e=>setPlanDraft({...planDraft,durationWeeks:e.target.value})} placeholder="Duration weeks" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input value={planDraft.teachingModes} onChange={e=>setPlanDraft({...planDraft,teachingModes:e.target.value})} placeholder="Teaching modes, comma separated" className="min-h-11 rounded-xl border border-slate-200 px-3"/></div><button disabled={saving==='plan'} onClick={()=>void savePlan()} className="min-h-11 mt-4 rounded-xl bg-brand-red text-white px-4 text-xs font-bold inline-flex items-center gap-2"><Save size={14}/>{saving==='plan'?'Saving…':'Save plan'}</button></div>}
  <div className="pro-surface rounded-2xl p-6"><h2 className="font-black mb-4">Monthly financial summary</h2><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-xs"><thead><tr className="border-b border-slate-200"><th className="p-3 text-left">Month</th><th className="p-3 text-left">Transactions</th><th className="p-3 text-left">Gross</th><th className="p-3 text-left">Gateway fees</th><th className="p-3 text-left">Tutor allocations</th><th className="p-3 text-left">Staff payouts</th><th className="p-3 text-left">Withdrawal fees</th><th className="p-3 text-left">Platform fee revenue</th></tr></thead><tbody>{monthly.length?monthly.map((m:any)=><tr key={m.month} className="border-b border-slate-100"><td className="p-3 font-bold">{m.month}</td><td className="p-3">{m.transactions}</td><td className="p-3">{money(m.gross)}</td><td className="p-3">{money(m.gatewayFees)}</td><td className="p-3">{money(m.tutorAllocated)}</td><td className="p-3">{money(m.withdrawals)}</td><td className="p-3">{money(m.withdrawalFees)}</td><td className="p-3 font-black">{money(m.platformRevenue)}</td></tr>):<tr><td colSpan={8} className="p-8 text-center text-slate-500">No verified financial activity yet.</td></tr>}</tbody></table></div></div>
  <div className="pro-surface rounded-2xl p-6"><h2 className="font-black mb-4">Verified payments & tutor assignment</h2><div className="overflow-x-auto"><table className="min-w-[1200px] w-full text-xs"><thead><tr className="border-b border-slate-200"><th className="p-3 text-left">Paid</th><th className="p-3 text-left">Plan</th><th className="p-3 text-left">Child / School</th><th className="p-3 text-left">Mode</th><th className="p-3 text-left">Duration</th><th className="p-3 text-left">Base</th><th className="p-3 text-left">Fee</th><th className="p-3 text-left">Total</th><th className="p-3 text-left">Tutor</th><th className="p-3 text-left">Assign</th></tr></thead><tbody>{paid.length?paid.map((p:any)=><tr key={p.id} className="border-b border-slate-100"><td className="p-3">{dateLabel(p.paidAt)}</td><td className="p-3"><div className="font-bold">{p.plan}</div><div className="text-slate-500">{p.reference}</div></td><td className="p-3">{p.studentName||p.enrollmentStudentName||'School account'}</td><td className="p-3">{p.teachingMode||'—'}</td><td className="p-3">{p.durationWeeks||'—'} weeks</td><td className="p-3">{money(p.baseAmount)}</td><td className="p-3">{money(p.transactionFee)}</td><td className="p-3 font-black">{money(p.customerTotal||Number(p.amount||0)/100)}</td><td className="p-3">{p.tutorName||'Unassigned'}</td><td className="p-3">{p.tutorId?<span className="inline-flex items-center gap-1 text-green-700"><CheckCircle2 size={13}/>Assigned</span>:<select defaultValue="" disabled={saving===p.id} onChange={e=>void assignTutor(p,e.target.value)} className="min-h-10 rounded-lg border border-slate-200 bg-white px-2"><option value="">Choose tutor</option>{(data.staff||[]).filter((s:any)=>['tutor','staff'].includes(String(s.role).toLowerCase())).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}</td></tr>):<tr><td colSpan={10} className="p-8 text-center text-slate-500">No verified payments yet.</td></tr>}</tbody></table></div></div>
  <div className="pro-surface rounded-2xl p-6"><h2 className="font-black mb-4">Staff withdrawals</h2><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-xs"><thead><tr className="border-b border-slate-200"><th className="p-3 text-left">Date</th><th className="p-3 text-left">Staff</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Gross</th><th className="p-3 text-left">Service fee</th><th className="p-3 text-left">Net payout</th><th className="p-3 text-left">Bank</th></tr></thead><tbody>{withdrawals.length?withdrawals.map((w:any)=><tr key={w.id} className="border-b border-slate-100"><td className="p-3">{dateLabel(w.paidAt||w.createdAt)}</td><td className="p-3">{w.staffName||w.staffId}</td><td className="p-3 font-bold">{w.status}</td><td className="p-3">{money(w.grossAmount||w.amount)}</td><td className="p-3">{money(w.serviceFee)}</td><td className="p-3 font-black">{money(w.netAmount)}</td><td className="p-3">•••• {w.bankLast4||'—'}</td></tr>):<tr><td colSpan={7} className="p-8 text-center text-slate-500">No staff withdrawals recorded.</td></tr>}</tbody></table></div></div>
  <div className="pro-surface rounded-2xl p-6"><h2 className="font-black mb-4">Enrollment/payment context</h2><div className="space-y-3">{(data.enrollments||[]).map((i:any)=><div key={i.id} className="rounded-xl border border-slate-200 dark:border-slate-800 p-4"><div className="grid grid-cols-1 md:grid-cols-3 gap-2 text-xs"><span><strong>Child:</strong> {i.studentName||'—'}</span><span><strong>Plan:</strong> {i.paymentPlanName||i.plan||'—'}</span><span><strong>Mode:</strong> {i.teachingMode||i.modeOfTeaching||'—'}</span><span><strong>Duration:</strong> {i.durationWeeks||'—'} weeks</span><span><strong>Total:</strong> {money(i.paymentTotal)}</span><span><strong>Status:</strong> {i.paymentStatus||i.status||'—'}</span></div></div>)}</div></div>
 </div>;
};
const Metric=({icon,label,value}:{icon:React.ReactNode;label:string;value:string})=><div className="pro-surface rounded-2xl p-5"><div>{icon}</div><div className="text-xs text-slate-500 mt-3">{label}</div><div className="text-xl font-black mt-1">{value}</div></div>;
const PolicyCard=({title,policy,setPolicy,saving,onSave}:{title:string;policy:Policy;setPolicy:(p:Policy)=>void;saving:boolean;onSave:()=>void})=><div className="pro-surface rounded-2xl p-6"><h2 className="font-black">{title}</h2><p className="text-xs text-slate-500 mt-1">Passed through to the customer; not credited to staff.</p><div className="grid grid-cols-2 gap-3 mt-4"><input type="number" step="0.01" value={policy.percentage} onChange={e=>setPolicy({...policy,percentage:e.target.value})} placeholder="Percent" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input type="number" value={policy.flat} onChange={e=>setPolicy({...policy,flat:e.target.value})} placeholder="Flat fee" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input type="number" value={policy.cap} onChange={e=>setPolicy({...policy,cap:e.target.value})} placeholder="Cap" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input type="number" value={policy.waiveFlatBelow||''} onChange={e=>setPolicy({...policy,waiveFlatBelow:e.target.value})} placeholder="Waive flat below" className="min-h-11 rounded-xl border border-slate-200 px-3"/></div><button disabled={saving} type="button" onClick={onSave} className="min-h-11 mt-4 rounded-xl bg-brand-slate text-white px-4 text-xs font-bold inline-flex items-center gap-2"><Save size={14}/>{saving?'Saving…':'Save policy'}</button></div>;
export default AdminBilling;
