import React, { useEffect, useMemo, useState } from 'react';
import { Activity, CheckCircle2, DollarSign, Edit3, Loader2, Save, ShieldCheck, Users, Wallet } from 'lucide-react';
import { billingGet, billingPost, dateLabel, formatNaira } from '../../lib/billing';
import SEO from '../../components/ui/SEO';
import { useToast } from '../../contexts/ToastContext';

type Plan = Record<string, any> & { id: string };

const AdminBilling: React.FC = () => {
  const { toast } = useToast();
  const [data, setData] = useState<any>({ config: { plans: {}, parentFeePolicy: {}, schoolFeePolicy: {} }, payments: [], enrollments: [], staff: [] });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState('');
  const [role, setRole] = useState('admin');
  const [selectedPlan, setSelectedPlan] = useState('');
  const [planDraft, setPlanDraft] = useState({ name: '', baseAmount: '', durationWeeks: '', teachingModes: '' });
  const [parentPolicy, setParentPolicy] = useState({ percentage: '', flat: '', cap: '', waiveFlatBelow: '', enabled: true });
  const [schoolPolicy, setSchoolPolicy] = useState({ percentage: '', flat: '', cap: '', waiveFlatBelow: '', enabled: true });
  const [minimumWithdrawal, setMinimumWithdrawal] = useState('10000');

  const load = async () => { setLoading(true); try { const result = await billingGet<any>('billing-data'); setData(result); const currentRole = String(sessionStorage.getItem('userRole') || result.role || 'admin').toLowerCase(); setRole(currentRole); setParentPolicy(result.config.parentFeePolicy); setSchoolPolicy(result.config.schoolFeePolicy); setMinimumWithdrawal(String(result.config.minimumWithdrawalAmount || 10000)); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to load billing operations.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);

  const plans = Object.values((data.config?.plans || {}) as Record<string, Plan>);
  const totalGross = useMemo(() => (data.payments || []).filter((p: any) => String(p.status).toUpperCase() === 'PAID').reduce((sum: number, p: any) => sum + Number(p.customerTotal || Number(p.amount || 0) / 100), 0), [data.payments]);
  const totalFees = useMemo(() => (data.payments || []).filter((p: any) => String(p.status).toUpperCase() === 'PAID').reduce((sum: number, p: any) => sum + Number(p.transactionFee || 0), 0), [data.payments]);
  const assigned = useMemo(() => (data.payments || []).filter((p: any) => p.tutorId).length, [data.payments]);

  const editPlan = (plan: Plan) => { setSelectedPlan(plan.id); setPlanDraft({ name: plan.name || '', baseAmount: String(plan.baseAmount ?? ''), durationWeeks: String(plan.durationWeeks ?? ''), teachingModes: Array.isArray(plan.teachingModes) ? plan.teachingModes.join(', ') : '' }); };
  const savePlan = async () => { if (!selectedPlan) return; setSaving('plan'); try { await billingPost('billing-admin', { action: 'update_plan', planId: selectedPlan, name: planDraft.name, baseAmount: Number(planDraft.baseAmount), durationWeeks: Number(planDraft.durationWeeks), teachingModes: planDraft.teachingModes.split(',').map(s => s.trim()).filter(Boolean) }); toast.success('Payment plan updated.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to save plan.'); } finally { setSaving(''); } };
  const savePolicy = async (policyRole: 'parent' | 'school', policy: any) => { setSaving(policyRole); try { await billingPost('billing-admin', { action: 'update_fee_policy', role: policyRole, percentage: Number(policy.percentage), flat: Number(policy.flat), cap: Number(policy.cap), waiveFlatBelow: Number(policy.waiveFlatBelow), enabled: policy.enabled }); toast.success(`${policyRole === 'parent' ? 'Parent' : 'School'} transaction fee policy updated.`); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to save fee policy.'); } finally { setSaving(''); } };
  const saveMinimum = async () => { setSaving('minimum'); try { await billingPost('billing-admin', { action: 'set_minimum_withdrawal', amount: Number(minimumWithdrawal) }); toast.success('Minimum withdrawal updated.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to save withdrawal policy.'); } finally { setSaving(''); } };
  const assignTutor = async (payment: any, tutorId: string) => { if (!tutorId) return; setSaving(payment.id); try { await billingPost('billing-admin', { action: 'assign_tutor', paymentId: payment.id, studentId: payment.studentId || '', tutorId }); toast.success('Tutor assigned and wallet allocation recorded.'); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Unable to assign tutor.'); } finally { setSaving(''); } };

  if (loading) return <div className="py-12 flex justify-center text-sm text-slate-500"><Loader2 className="animate-spin mr-2" size={18}/>Loading billing operations...</div>;
  return <div className="space-y-6"><SEO title="Billing & Wallet Operations | Admin" description="Manage payment plans, fees, transactions and staff wallet allocations." noindex={true}/>
    <div className="pro-surface rounded-3xl p-6 md:p-8"><div className="flex items-center justify-between gap-4"><div><div className="text-brand-red font-black text-xs uppercase tracking-widest flex items-center gap-2"><ShieldCheck size={14}/> Financial Operations</div><h1 className="text-2xl md:text-3xl font-black mt-2">Billing, Paystack & Staff Wallets</h1><p className="text-sm text-slate-500 mt-1">One source of truth for plans, transaction fees, paid-through dates, tutor assignments and withdrawals.</p></div><button type="button" onClick={() => void load()} className="min-h-11 rounded-xl border border-slate-200 px-4 text-xs font-bold">Refresh</button></div></div>
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4"><div className="pro-surface rounded-2xl p-5"><DollarSign size={18}/><div className="text-xs text-slate-500 mt-3">Gross verified</div><div className="text-2xl font-black">{formatNaira(totalGross)}</div></div><div className="pro-surface rounded-2xl p-5"><Activity size={18}/><div className="text-xs text-slate-500 mt-3">Gateway fees collected</div><div className="text-2xl font-black">{formatNaira(totalFees)}</div></div><div className="pro-surface rounded-2xl p-5"><Users size={18}/><div className="text-xs text-slate-500 mt-3">Tutor-linked payments</div><div className="text-2xl font-black">{assigned}</div></div><div className="pro-surface rounded-2xl p-5"><Wallet size={18}/><div className="text-xs text-slate-500 mt-3">Minimum withdrawal</div><div className="text-2xl font-black">{formatNaira(data.config?.minimumWithdrawalAmount)}</div></div></div>
    <div className="pro-surface rounded-2xl p-6"><div className="flex items-center justify-between mb-5"><div><h2 className="font-black">Payment plans</h2><p className="text-xs text-slate-500 mt-1">Only the super admin can change pricing. Changes apply to new checkouts.</p></div><Edit3 size={18}/></div><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{plans.map(plan => <div key={plan.id} className="rounded-2xl border border-slate-200 dark:border-slate-800 p-4"><div className="font-black">{plan.name}</div><div className="text-xs text-slate-500 mt-1">{plan.role} • {plan.durationWeeks} weeks</div><div className="text-2xl font-black mt-2">{formatNaira(plan.baseAmount)}</div><div className="text-xs text-slate-500 mt-2">{(plan.teachingModes || []).join(' • ')}</div>{role === 'superadmin' && <button type="button" onClick={() => editPlan(plan)} className="min-h-10 mt-4 rounded-lg border border-slate-200 px-3 text-xs font-bold">Edit plan</button>}</div>)}</div></div>
    {selectedPlan && role === 'superadmin' && <div className="pro-surface rounded-2xl p-6"><div className="flex items-center justify-between"><h2 className="font-black">Edit plan</h2><button type="button" onClick={() => setSelectedPlan('')} className="text-xs font-bold">Close</button></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4"><input value={planDraft.name} onChange={e => setPlanDraft({ ...planDraft, name: e.target.value })} placeholder="Plan name" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input type="number" value={planDraft.baseAmount} onChange={e => setPlanDraft({ ...planDraft, baseAmount: e.target.value })} placeholder="Base amount" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input type="number" value={planDraft.durationWeeks} onChange={e => setPlanDraft({ ...planDraft, durationWeeks: e.target.value })} placeholder="Duration weeks" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input value={planDraft.teachingModes} onChange={e => setPlanDraft({ ...planDraft, teachingModes: e.target.value })} placeholder="Teaching modes, comma separated" className="min-h-11 rounded-xl border border-slate-200 px-3"/></div><button disabled={saving === 'plan'} onClick={() => void savePlan()} className="min-h-11 mt-4 rounded-xl bg-brand-red text-white px-4 text-xs font-bold inline-flex items-center gap-2"><Save size={14}/>{saving === 'plan' ? 'Saving…' : 'Save plan'}</button></div>}
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">{([{ role: 'parent', title: 'Parent transaction fee', policy: parentPolicy, setPolicy: setParentPolicy }, { role: 'school', title: 'School transaction fee', policy: schoolPolicy, setPolicy: setSchoolPolicy }] as const).map(section => <div key={section.role} className="pro-surface rounded-2xl p-6"><h2 className="font-black">{section.title}</h2><p className="text-xs text-slate-500 mt-1">The fee is passed through to the customer; it is not credited to staff.</p><div className="grid grid-cols-2 gap-3 mt-4"><input disabled={role !== 'superadmin'} type="number" step="0.01" value={section.policy.percentage} onChange={e => section.setPolicy({ ...section.policy, percentage: e.target.value })} placeholder="Percent" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input disabled={role !== 'superadmin'} type="number" value={section.policy.flat} onChange={e => section.setPolicy({ ...section.policy, flat: e.target.value })} placeholder="Flat fee" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input disabled={role !== 'superadmin'} type="number" value={section.policy.cap} onChange={e => section.setPolicy({ ...section.policy, cap: e.target.value })} placeholder="Cap" className="min-h-11 rounded-xl border border-slate-200 px-3"/><input disabled={role !== 'superadmin'} type="number" value={section.policy.waiveFlatBelow} onChange={e => section.setPolicy({ ...section.policy, waiveFlatBelow: e.target.value })} placeholder="Waive flat below" className="min-h-11 rounded-xl border border-slate-200 px-3"/></div>{role === 'superadmin' && <button disabled={saving === section.role} type="button" onClick={() => void savePolicy(section.role, section.policy)} className="min-h-11 mt-4 rounded-xl bg-brand-slate text-white px-4 text-xs font-bold inline-flex items-center gap-2"><Save size={14}/>Save policy</button>}</div>)}</div>
    {role === 'superadmin' && <div className="pro-surface rounded-2xl p-6"><h2 className="font-black">Wallet withdrawal rule</h2><div className="flex gap-3 mt-4"><input type="number" value={minimumWithdrawal} onChange={e => setMinimumWithdrawal(e.target.value)} className="min-h-11 rounded-xl border border-slate-200 px-3"/><button disabled={saving === 'minimum'} type="button" onClick={() => void saveMinimum()} className="min-h-11 rounded-xl bg-brand-slate text-white px-4 text-xs font-bold">Save minimum</button></div></div>}
    <div className="pro-surface rounded-2xl p-6"><h2 className="font-black mb-4">Verified payments</h2><div className="overflow-x-auto"><table className="min-w-[1200px] w-full text-xs"><thead><tr className="border-b border-slate-200"><th className="p-3 text-left">Paid</th><th className="p-3 text-left">Plan</th><th className="p-3 text-left">Child / School</th><th className="p-3 text-left">Mode</th><th className="p-3 text-left">Duration</th><th className="p-3 text-left">Base</th><th className="p-3 text-left">Fee</th><th className="p-3 text-left">Total</th><th className="p-3 text-left">Tutor</th><th className="p-3 text-left">Assign</th></tr></thead><tbody>{(data.payments || []).filter((p: any) => String(p.status).toUpperCase() === 'PAID').map((payment: any) => <tr key={payment.id} className="border-b border-slate-100"><td className="p-3">{dateLabel(payment.paidAt)}</td><td className="p-3"><div className="font-bold">{payment.plan}</div><div className="text-slate-500">{payment.reference}</div></td><td className="p-3">{payment.studentName || 'School account'}</td><td className="p-3">{payment.teachingMode || '—'}</td><td className="p-3">{payment.durationWeeks || '—'} weeks</td><td className="p-3">{formatNaira(payment.baseAmount)}</td><td className="p-3">{formatNaira(payment.transactionFee)}</td><td className="p-3 font-black">{formatNaira(payment.customerTotal || Number(payment.amount || 0) / 100)}</td><td className="p-3">{payment.tutorName || 'Unassigned'}</td><td className="p-3">{payment.tutorId ? <span className="inline-flex items-center gap-1 text-green-700"><CheckCircle2 size={13}/>Assigned</span> : <select defaultValue="" disabled={saving === payment.id} onChange={e => void assignTutor(payment, e.target.value)} className="min-h-10 rounded-lg border border-slate-200 bg-white px-2"><option value="">Choose tutor</option>{(data.staff || []).filter((s: any) => ['tutor','staff'].includes(String(s.role).toLowerCase())).map((staff: any) => <option key={staff.id} value={staff.id}>{staff.name}</option>)}</select>}</td></tr>)}</tbody></table></div></div>
    <div className="pro-surface rounded-2xl p-6"><h2 className="font-black mb-4">Enrollment/payment context</h2><div className="space-y-3">{(data.enrollments || []).map((item: any) => <div key={item.id} className="rounded-xl border border-slate-200 dark:border-slate-800 p-4"><div className="grid grid-cols-1 md:grid-cols-3 gap-2 text-xs"><span><strong>Child:</strong> {item.studentName || '—'}</span><span><strong>Plan:</strong> {item.paymentPlanName || item.plan || '—'}</span><span><strong>Mode:</strong> {item.teachingMode || item.modeOfTeaching || '—'}</span><span><strong>Duration:</strong> {item.durationWeeks || '—'} weeks</span><span><strong>Total:</strong> {formatNaira(item.paymentTotal)}</span><span><strong>Status:</strong> {item.paymentStatus || item.status || '—'}</span></div></div>)}</div></div>
  </div>;
};

export default AdminBilling;
