import React, { useEffect, useMemo, useState } from 'react';
import { collection, onSnapshot } from 'firebase/firestore';
import { BarChart3, Download, RefreshCw, Users, School, CreditCard, ClipboardList, Activity, FileSpreadsheet } from 'lucide-react';
import { db } from '../../lib/firebase';

const money = (value: number) => `₦${Math.round(value || 0).toLocaleString('en-NG')}`;
const dateValue = (value: any) => value?.toDate ? value.toDate() : value ? new Date(value) : null;
const csv = (rows: string[][]) => rows.map(row => row.map(value => `"${String(value ?? '').replace(/"/g, '""').replace(/\r?\n/g, ' ')}"`).join(',')).join('\n');

const AdminReports: React.FC = () => {
  const [users, setUsers] = useState<any[]>([]); const [schools, setSchools] = useState<any[]>([]); const [students, setStudents] = useState<any[]>([]); const [payments, setPayments] = useState<any[]>([]); const [inquiries, setInquiries] = useState<any[]>([]); const [activity, setActivity] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [range, setRange] = useState('all');

  useEffect(() => {
    setLoading(true);
    const unsubs = [
      ['users', setUsers], ['schools', setSchools], ['students', setStudents], ['payments', setPayments], ['inquiries', setInquiries], ['activityLogs', setActivity]
    ].map(([name, setter]) => onSnapshot(collection(db, name as string), snap => (setter as React.Dispatch<React.SetStateAction<any[]>>)(snap.docs.map(d => ({ id: d.id, ...d.data() }))), error => console.error(`Reports ${name}`, error)));
    const timer = window.setTimeout(() => setLoading(false), 900);
    return () => { unsubs.forEach(unsub => unsub()); window.clearTimeout(timer); };
  }, []);

  const cutoff = useMemo(() => { if (range === 'all') return null; const days = Number(range); const value = new Date(); value.setDate(value.getDate() - days); return value; }, [range]);
  const within = (item: any) => !cutoff || !dateValue(item.createdAt || item.timestamp || item.paidAt || item.updatedAt) || (dateValue(item.createdAt || item.timestamp || item.paidAt || item.updatedAt) as Date) >= cutoff;
  const scoped = (items: any[]) => items.filter(within);
  const data = useMemo(() => {
    const u = scoped(users), s = scoped(schools), st = scoped(students), p = scoped(payments), i = scoped(inquiries), a = scoped(activity);
    const successfulPayments = p.filter(x => ['success','successful','paid','confirmed','completed'].includes(String(x.status || x.paymentStatus || '').toLowerCase()));
    const revenue = successfulPayments.reduce((sum, x) => sum + Number(x.baseAmount ?? x.amount ?? x.total ?? 0), 0);
    return { users: u, schools: s, students: st, payments: p, inquiries: i, activity: a, successfulPayments, revenue, tutors: u.filter(x => ['TUTOR','STAFF','INSTRUCTOR'].includes(String(x.role || '').toUpperCase())), parents: u.filter(x => String(x.role || '').toUpperCase() === 'PARENT'), schoolUsers: u.filter(x => String(x.role || '').toUpperCase() === 'SCHOOL') };
  }, [users, schools, students, payments, inquiries, activity, cutoff]);

  const exportReport = (name: string, rows: string[][]) => { const blob = new Blob([csv(rows)], { type: 'text/csv;charset=utf-8;' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `jaystarbliss-${name}-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); };
  const exportAll = () => exportReport('admin-report', [['Metric','Value'],['Users',String(data.users.length)],['Schools',String(data.schools.length)],['Students',String(data.students.length)],['Parents',String(data.parents.length)],['Tutors / Staff',String(data.tutors.length)],['School Accounts',String(data.schoolUsers.length)],['Inquiries',String(data.inquiries.length)],['Successful Payments',String(data.successfulPayments.length)],['Recorded Revenue',String(data.revenue)],['Audit Events',String(data.activity.length)]]);

  const cards = [
    { label: 'Active schools', value: data.schools.filter(x => String(x.status || '').toUpperCase() === 'ACTIVE').length, icon: School },
    { label: 'Students', value: data.students.length, icon: Users },
    { label: 'Successful payments', value: data.successfulPayments.length, icon: CreditCard },
    { label: 'Audit events', value: data.activity.length, icon: Activity },
  ];

  return <div className="space-y-7 pb-10">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-brand-red text-xs font-black uppercase tracking-[0.18em]"><BarChart3 size={14}/> Management intelligence</div><h1 className="mt-1 text-2xl sm:text-3xl font-black text-slate-900 dark:text-white">Reports & Analytics</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500 dark:text-slate-400">One reporting surface for institutional, academic, financial and operational activity. Values are calculated from the live Firestore records available to the administrator.</p></div><div className="flex flex-wrap gap-2"><select value={range} onChange={e => setRange(e.target.value)} className="min-h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold text-slate-700 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200"><option value="all">All time</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last 12 months</option></select><button type="button" onClick={exportAll} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-brand-red px-4 py-2.5 text-sm font-black text-white shadow-sm hover:bg-red-700"><Download size={16}/> Export summary</button></div></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card => { const Icon = card.icon; return <div key={card.label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase tracking-wider text-slate-400">{card.label}</span><Icon size={18} className="text-brand-red"/></div><strong className="mt-3 block text-3xl font-black text-slate-900 dark:text-white">{loading ? '—' : card.value.toLocaleString()}</strong></div>; })}</section>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-black text-slate-900 dark:text-white">Institutional report</h2><p className="mt-1 text-xs text-slate-500">Schools, school accounts and student population.</p></div><button type="button" onClick={() => exportReport('institutional', [['Metric','Value'],['Schools',String(data.schools.length)],['Active schools',String(data.schools.filter(x => String(x.status || '').toUpperCase() === 'ACTIVE').length)],['School administrators',String(data.schoolUsers.length)],['Students',String(data.students.length)]])} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-xs font-bold dark:border-slate-700"><FileSpreadsheet size={14}/> CSV</button></div><div className="mt-5 grid grid-cols-2 gap-3">{[['Total schools',data.schools.length],['Active schools',data.schools.filter(x => String(x.status || '').toUpperCase() === 'ACTIVE').length],['School accounts',data.schoolUsers.length],['Students',data.students.length]].map(([label,value]) => <div key={String(label)} className="rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><span className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</span><strong className="mt-1 block text-xl text-slate-900 dark:text-white">{Number(value).toLocaleString()}</strong></div>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-black text-slate-900 dark:text-white">Financial report</h2><p className="mt-1 text-xs text-slate-500">Gateway-confirmed payments use the stored base amount; customer fee data remains separate.</p></div><button type="button" onClick={() => exportReport('financial', [['Metric','Value'],['Successful payments',String(data.successfulPayments.length)],['Recorded base revenue',String(data.revenue)],['Pending / other payments',String(data.payments.length - data.successfulPayments.length)]])} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-xs font-bold dark:border-slate-700"><FileSpreadsheet size={14}/> CSV</button></div><div className="mt-5 space-y-3"><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><span className="text-[10px] font-black uppercase tracking-wider text-slate-400">Recorded successful base revenue</span><strong className="mt-1 block text-2xl font-black text-slate-900 dark:text-white">{money(data.revenue)}</strong></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><span className="text-[10px] font-black uppercase tracking-wider text-slate-400">Confirmed</span><strong className="mt-1 block text-xl text-slate-900 dark:text-white">{data.successfulPayments.length}</strong></div><div className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><span className="text-[10px] font-black uppercase tracking-wider text-slate-400">Other</span><strong className="mt-1 block text-xl text-slate-900 dark:text-white">{Math.max(0,data.payments.length - data.successfulPayments.length)}</strong></div></div></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-black text-slate-900 dark:text-white">Academic / people report</h2><p className="mt-1 text-xs text-slate-500">Students, parents and instructional personnel.</p></div><ClipboardList size={18} className="text-brand-red"/></div><div className="mt-5 space-y-2">{[['Students',data.students.length],['Parents',data.parents.length],['Tutors / staff',data.tutors.length],['School administrators',data.schoolUsers.length]].map(([label,value]) => <div key={String(label)} className="flex items-center justify-between rounded-xl border border-slate-100 px-4 py-3 dark:border-slate-800"><span className="text-sm font-semibold text-slate-600 dark:text-slate-300">{label}</span><strong className="text-sm font-black text-slate-900 dark:text-white">{Number(value).toLocaleString()}</strong></div>)}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-black text-slate-900 dark:text-white">CRM & operations</h2><p className="mt-1 text-xs text-slate-500">Lead pipeline and system activity.</p></div><button type="button" onClick={() => exportReport('operations', [['Metric','Value'],['Inquiries',String(data.inquiries.length)],['Converted',String(data.inquiries.filter(x => String(x.status || '').toUpperCase() === 'CONVERTED').length)],['Audit events',String(data.activity.length)]])} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-slate-200 px-3 text-xs font-bold dark:border-slate-700"><FileSpreadsheet size={14}/> CSV</button></div><div className="mt-5 space-y-2">{[['Inquiries',data.inquiries.length],['Converted leads',data.inquiries.filter(x => String(x.status || '').toUpperCase() === 'CONVERTED').length],['Open / active leads',data.inquiries.filter(x => !['CLOSED','LOST'].includes(String(x.status || '').toUpperCase())).length],['Audit events',data.activity.length]].map(([label,value]) => <div key={String(label)} className="flex items-center justify-between rounded-xl border border-slate-100 px-4 py-3 dark:border-slate-800"><span className="text-sm font-semibold text-slate-600 dark:text-slate-300">{label}</span><strong className="text-sm font-black text-slate-900 dark:text-white">{Number(value).toLocaleString()}</strong></div>)}</div></section>
    </div>
    <div className="flex items-center gap-2 text-xs text-slate-400"><RefreshCw size={13}/> Live data refreshes automatically when the underlying collections change.</div>
  </div>;
};
export default AdminReports;
